syntax = "proto3";


import "_FilmfestBallGameAction.proto";
import "_FilmfestBallGameSyncCreateConnect.proto";
import "AGBEDALGLKB.proto";
import "ANOICJCLKMF.proto";

message _FilmfestBallGameSnapShot {
	uint64 client_game_time = 1;
	uint64 server_game_time = 2;
	repeated AGBEDALGLKB entity_list = 3;
	repeated _FilmfestBallGameAction action_list = 4;
	bool is_finish = 5;
	repeated uint32 id_index_list = 6;
	int32 raw_client_game_time = 7;
	repeated ANOICJCLKMF player_info_list = 8;
	int32 wave_index = 9;
	_FilmfestBallGameSyncCreateConnect CKABLNNANPP = 10;
	int32 LNOBOOAACMK = 11;
	int32 BDIKCMCEDFF = 12;
	uint32 POLHOAJOFGL = 13;
	uint32 IAMEDLBNEDE = 14;
	uint32 IPPOFDODFAP = 15;
	uint32 LCHDPCEAEEM = 16;
	uint32 stage_index = 17;
	int32 HKACKOLBEBC = 18;
}
