syntax = "proto3";


import "_InvestigationMonsterConfig.proto";
import "Vector.proto";
import "WeeklyBossResinDiscountInfo.proto";

message _InvestigationMonsterDetail {
	Vector pos = 4;
	WeeklyBossResinDiscountInfo weekly_boss_resin_discount_info = 7;
	_InvestigationMonsterConfig _monster_config = 1;
	bool is_area_locked = 13;
	bool _is_respawning = 3;
	bool is_alive = 10;
	uint32 boss_chest_num = 6;
	uint32 max_boss_chest_num = 8;
	uint32 refresh_interval = 9;
	uint32 next_boss_chest_refresh_time = 14;
	uint32 _map_layer_id = 2;
	uint32 resin = 11;
	uint32 next_refresh_time = 15;
	uint32 level = 5;
}
