syntax = "proto3";

import "AbilityAttachedModifier.proto";
import "AbilityString.proto";
import "ModifierAction.proto";
import "ModifierProperty.proto";

message AbilityMetaModifierChange {
	AbilityString parent_ability_override = 1;
	AbilityAttachedModifier attached_instanced_modifier = 9;
	repeated ModifierProperty properties = 12;
	AbilityString parent_ability_name = 13;
	uint32 server_buff_uid = 5;
	ModifierAction action = 4;
	bool PFKEFMHBGPK = 2;
	bool BFFGKGIHNON = 8;
	bool is_attached_parent_ability = 10;
	uint32 apply_entity_id = 15;
	uint64 ANOCMABMMON = 7;
	int32 modifier_local_id = 3;
	float CHODOKOCJMC = 14;
}