syntax = "proto3";

import "ActivityPushTipsData.proto";
import "ActivityWatcherInfo.proto";
import "ArenaChallengeActivityDetailInfo.proto";
import "AsterActivityDetailInfo.proto";
import "BartenderActivityDetailInfo.proto";
import "BDIILDOBHIO.proto";
import "BlessingActivityDetailInfo.proto";
import "BlitzRushActivityDetailInfo.proto";
import "BounceConjuringActivityDetailInfo.proto";
import "BrickBreakerDetailInfo.proto";
import "BuoyantCombatDetailInfo.proto";
import "ChannelerSlabActivityDetailInfo.proto";
import "CharAmusementDetailInfo.proto";
import "ChessActivityDetailInfo.proto";
import "CoinCollectDetailInfo.proto";
import "CrucibleActivityDetailInfo.proto";
import "CrystalLinkActivityDetailInfo.proto";
import "DeliveryActivityDetailInfo.proto";
import "DigActivityDetailInfo.proto";
import "DragonSpineActivityDetailInfo.proto";
import "DuelHeartDetailInfo.proto";
import "EchoShellDetailInfo.proto";
import "EffigyActivityDetailInfo.proto";
import "EffigyChallengeV2DetailInfo.proto";
import "ElectroherculesBattleDetailInfo.proto";
import "ExpeditionActivityDetailInfo.proto";
import "FindHilichurlDetailInfo.proto";
import "FleurFairActivityDetailInfo.proto";
import "FlightActivityDetailInfo.proto";
import "FungusFighterDetailInfo.proto";
import "GachaActivityDetailInfo.proto";
import "GCGFestivalDetailInfo.proto";
import "GearActivityDetailInfo.proto";
import "GravenInnocenceDetailInfo.proto";
import "HachiActivityDetailInfo.proto";
import "HideAndSeekActivityDetailInfo.proto";
import "InstableSprayDetailInfo.proto";
import "IrodoriActivityDetailInfo.proto";
import "IslandPartyDetailInfo.proto";
import "LanternRiteActivityDetailInfo.proto";
import "LuminanceStoneChallengeActivityDetailInfo.proto";
import "LunaRiteDetailInfo.proto";
import "MichiaeMatsuriActivityDetailInfo.proto";
import "MistTrialActivityDetailInfo.proto";
import "MoonfinTrialActivityDetailInfo.proto";
import "MuqadasPotionActivityDetailInfo.proto";
import "MusicGameActivityDetailInfo.proto";
import "PhotoActivityDetailInfo.proto";
import "PlantFlowerActivityDetailInfo.proto";
import "PotionActivityDetailInfo.proto";
import "RockBoardExploreDetailInfo.proto";
import "RogueDiaryActivityDetailInfo.proto";
import "RoguelikeDungeonActivityDetailInfo.proto";
import "SalesmanActivityDetailInfo.proto";
import "SeaLampActivityDetailInfo.proto";
import "SeaLampActivityInfo.proto";
import "SeaLampV3DetailInfo.proto";
import "SpiceActivityDetailInfo.proto";
import "SummerTimeDetailInfo.proto";
import "SummerTimeV2DetailInfo.proto";
import "SumoActivityDetailInfo.proto";
import "TanukiTravelActivityDetailInfo.proto";
import "TeamChainDetailInfo.proto";
import "TreasureMapActivityDetailInfo.proto";
import "TreasureSeelieActivityDetailInfo.proto";
import "TrialAvatarActivityDetailInfo.proto";
import "UgcActivityDetailInfo.proto";
import "VintageActivityDetailInfo.proto";
import "WaterSpiritActivityDetailInfo.proto";
import "WindFieldDetailInfo.proto";
import "WinterCampActivityDetailInfo.proto";

message ActivityInfo {
	repeated 
	repeated ActivityWatcherInfo watcher_info_list = 7;
	
	repeated 
	repeated 
	map<uint32, uint32> activity_coin_map = 193;
	BDIILDOBHIO JCAFPINKDJO = 1466;
	repeated ActivityPushTipsData activity_push_tips_data_list = 1750;
	
	map<uint32, uint32> wish_gift_num_map = 22;
	repeated 
	repeated 
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	oneof detail {
		
		
		
		
		
		ExpeditionActivityDetailInfo expedition_info = 394;
		CrucibleActivityDetailInfo crucible_info = 8;
		
		
		
		ChannelerSlabActivityDetailInfo challneler_slab_info = 1031;
		TeamChainDetailInfo team_chain_info = 2011;
		
		FindHilichurlDetailInfo find_hilichurl_info = 792;
		PotionActivityDetailInfo potion_info = 1253;
		
		
		
		HideAndSeekActivityDetailInfo hide_and_seek_info = 1218;
		EchoShellDetailInfo echo_shell_info = 1556;
		GachaActivityDetailInfo gacha_info = 1461;
		
		WaterSpiritActivityDetailInfo water_spirit_info = 1612;
		
		LunaRiteDetailInfo luna_rite_info = 1448;
		DigActivityDetailInfo dig_info = 1550;
		
		
		
		
		
		IslandPartyDetailInfo island_party_info = 1529;
		
		
		
		LanternRiteActivityDetailInfo lantern_rite_activity_info = 1514;
		
		MusicGameActivityDetailInfo music_game_info = 658;
		
		FleurFairActivityDetailInfo fleur_fair_info = 788;
		PlantFlowerActivityDetailInfo plant_flower_info = 415;
		InstableSprayDetailInfo instable_spray_info = 1605;
		RockBoardExploreDetailInfo rock_board_explore_info = 1518;
		
		
		
		FlightActivityDetailInfo flight_info = 800;
		
		
		BlessingActivityDetailInfo blessing_info = 323;
		
		LuminanceStoneChallengeActivityDetailInfo luminance_stone_challenge_info = 785;
		
		HachiActivityDetailInfo hachi_info = 1776;
		
		UgcActivityDetailInfo ugc_info = 770;
		RogueDiaryActivityDetailInfo rogue_diary_info = 1438;
		TanukiTravelActivityDetailInfo tanuki_travel_activity_info = 828;
		
		MistTrialActivityDetailInfo mist_trial_activity_info = 2001;
		
		CrystalLinkActivityDetailInfo crystal_link_info = 1796;
		
		
		EffigyActivityDetailInfo effigy_info = 130;
		
		
		
		ElectroherculesBattleDetailInfo electrohercules_battle_info = 1112;
		
		
		
		GearActivityDetailInfo gear_info = 1573;
		
		SeaLampV3DetailInfo sea_lamp_v3_info = 611;
		
		DuelHeartDetailInfo duel_heart_info = 133;
		SeaLampActivityDetailInfo sam_lamp_info = 12;
		GCGFestivalDetailInfo gcg_festival_info = 1054;
		ChessActivityDetailInfo chess_info = 1778;
		
		
		
		
		
		DragonSpineActivityDetailInfo dragon_spine_info = 1885;
		
		
		
		TrialAvatarActivityDetailInfo trial_avatar_info = 1;
		
		
		BartenderActivityDetailInfo bartender_info = 1635;
		WinterCampActivityDetailInfo winter_camp_info = 902;
		
		
		
		MoonfinTrialActivityDetailInfo moonfin_trial_info = 349;
		SeaLampActivityInfo sea_lamp_info = 1963;
		
		BlitzRushActivityDetailInfo blitz_rush_info = 357;
		
		ArenaChallengeActivityDetailInfo arena_challenge_info = 1954;
		
		
		
		
		
		AsterActivityDetailInfo aster_info = 1990;
		
		RoguelikeDungeonActivityDetailInfo roguelike_dungoen_info = 507;
		
		SpiceActivityDetailInfo spice_info = 1272;
		GravenInnocenceDetailInfo graven_innocence_info = 1302;
		SalesmanActivityDetailInfo salesman_info = 10;
		
		
		PhotoActivityDetailInfo photo_info = 810;
		
		WindFieldDetailInfo wind_field_info = 79;
		CoinCollectDetailInfo coin_collect_info = 1519;
		BrickBreakerDetailInfo brick_breaker_info = 104;
		
		
		
		CharAmusementDetailInfo char_amusement_info = 1183;
		DeliveryActivityDetailInfo delivery_info = 303;
		MuqadasPotionActivityDetailInfo muqadas_potion_info = 1298;
		
		SummerTimeV2DetailInfo summer_time_v2_info = 1355;
		SummerTimeDetailInfo summer_time_info = 1467;
		BounceConjuringActivityDetailInfo bounce_conjuring_info = 1071;
		VintageActivityDetailInfo vintage_info = 2003;
		BuoyantCombatDetailInfo buoyant_combat_info = 162;
		
		
		
		
		EffigyChallengeV2DetailInfo effigy_challenge_info = 1465;
		
		FungusFighterDetailInfo fungus_fighter_info = 1219;
		
		TreasureSeelieActivityDetailInfo treasure_seelie_info = 1870;
		IrodoriActivityDetailInfo irodori_info = 2026;
		
		SumoActivityDetailInfo sumo_info = 185;
		
		
		TreasureMapActivityDetailInfo treasure_map_info = 667;
		MichiaeMatsuriActivityDetailInfo michiae_matsuri_info = 839;
		
	}
}