syntax = "proto3";

import "AbilityIdentifier.proto";
import "AttackHitEffectResult.proto";
import "EMHFMKMJKLI.proto";
import "FCNANEKDOJP.proto";
import "HitCollision.proto";
import "ICFJCKPMDGJ.proto";
import "Vector.proto";

message AttackResult {
	AbilityIdentifier ability_identifier = 5;
	repeated 
	FCNANEKDOJP JPGIEAMPBOH = 762;
	EMHFMKMJKLI DJKJDEFMKOG = 1860;
	AttackHitEffectResult hit_eff_result = 4;
	Vector KEJPIBGGFBP = 719;
	ICFJCKPMDGJ AALLMDMBCCN = 438;
	Vector NBCLFHLIIGF = 8;
	HitCollision hit_collision = 2;
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
}