syntax = "proto3";


import "AvatarInfo.proto";
import "AvatarRenameInfo.proto";
import "AvatarTeam.proto";

message AvatarDataNotify {
	map<uint32, AvatarTeam> avatar_team_map = 7;
	repeated AvatarInfo avatar_list = 3;
	repeated AvatarRenameInfo avatar_rename_list = 9;
	repeated uint32 owned_flycloak_list = 10;
	repeated uint32 backup_avatar_team_order_list = 13;
	repeated uint32 _owned_trace_effect_list = 2;
	repeated uint64 temp_avatar_guid_list = 1;
	repeated uint32 owned_costume_list = 14;
	uint32 cur_avatar_team_id = 11;
	uint64 choose_avatar_guid = 4;
}
