syntax = "proto3";

import "AvatarEquipAffixInfo.proto";
import "AvatarExcelInfo.proto";
import "AvatarExpeditionState.proto";
import "AvatarFetterInfo.proto";
import "MirrorAvatarInfo.proto";
import "TrialAvatarInfo.proto";

message AvatarInfo {
	
	
	map<uint32, PropValue> prop_map = 3;
	
	repeated 
	repeated 
	map<uint32, float> fight_prop_map = 7;
	TrialAvatarInfo trial_avatar_info = 9;
	map<uint32, AvatarSkillInfo> skill_map = 10;
	
	AvatarFetterInfo fetter_info = 12;
	
	repeated 
	map<uint32, uint32> skill_level_map = 15;
	AvatarExpeditionState expedition_state = 16;
	map<uint32, uint32> proud_skill_extra_level_map = 17;
	
	
	repeated 
	
	repeated AvatarEquipAffixInfo equip_affix_list = 22;
	
	repeated 
	
	AvatarExcelInfo excel_info = 26;
	
	MirrorAvatarInfo mirror_avatar_info = 28;
	
	
	
	
	
	
	repeated 
	repeated 
}