syntax = "proto3";

import "BeyondProfilePicture.proto";
import "BeyondProfileTag.proto";
import "FeatureBlockType.proto";
import "ProfilePicture.proto";

message BeyondPlayerSocialInfo {
	uint32 uid = 1;
	uint32 _beyond_player_level = 2;
	_BeyondProfilePicture _beyond_profile_picture = 3;
	string nickname = 4;
	string signature = 5;
	uint32 _total_achievement_value = 8;
	uint32 _total_social_value = 9;
	uint32 platform_type = 10;
	bool GAILPOJNCKL = 11;
	string online_id = 12;
	string HADOFGGLMDB = 13;
	repeated uint32 blacklist_uid_list = 14;
	string _xbox_id = 15;
	uint32 _total_fashion_value = 16;
	map<uint32, uint32> PEOBPHGKEMF = 17;
	uint32 name_card_id = 18;
	repeated _BeyondProfileTag _beyond_profile_tag_list = 19;
	uint32 LJGIMBCLJCG = 20;
	bool LODLCABIAOI = 21;
	uint32 _creator_level = 22;
	ProfilePicture profile_picture = 23;
	uint32 CNABCHGNACK = 24;
	bool ICBLIHFIEDM = 26;
	bool _is_allow_stranger_chat = 27;
	bool KOBFFPKONGE = 28;
	bool FJHJLFLEJFI = 29;
	repeated FeatureBlockType NGLAGEBDGBJ = 30;
}
