syntax = "proto3";

import "ActionPointsNoCostBuffInfo.proto";
import "AddTotalRevenueAfterActionsExecBuffInfo.proto";
import "ExpandToReduceUpgradeCostBuffInfo.proto";
import "HireLevelUpgradeBuffInfo.proto";
import "NoQuestApCostAfterQuestFinishBuffInfo.proto";
import "RevenueBonusBuffInfo.proto";
import "UpgradeToBonusFacilityRevenueBuffInfo.proto";

message BIKNFNGIEJA {
	uint32 buff_id = 8;
	uint32 guid = 5;
	uint32 level = 9;
	uint32 FELAEJEDKJK = 13;
	uint32 NPGGKCNMJIK = 12;
	oneof detail {
		_RevenueBonusBuffInfo revenue_bonus_buff_info = 150;
		_ExpandToReduceUpgradeCostBuffInfo expand_to_reduce_upgrade_cost_buff_info = 121;
		_HireLevelUpgradeBuffInfo hire_level_upgrade_buff_info = 697;
		_NoQuestApCostAfterQuestFinishBuffInfo no_quest_ap_cost_after_quest_finish_buff_info = 1105;
		_UpgradeToBonusFacilityRevenueBuffInfo upgrade_to_bonus_facility_revenue_buff_info = 2035;
		_AddTotalRevenueAfterActionsExecBuffInfo add_total_revenue_after_actions_exec_buff_info = 771;
		_ActionPointsNoCostBuffInfo action_points_no_cost_buff_info = 1899;
	}
}
