syntax = "proto3";



message ChatInfo {
	message SystemHint {
		repeated 
		
	}

	message _BeyondCollectionNewCaptain {
		
		
		
	}

	message _HallInvitation {
		repeated 
		
		
		
		
		
		
	}

	message _BeyondTeamInvitation {
		
		
		
		
	}

	message _BeyondTeamApplication {
		
		
		
		
	}

	message _BeyondTeamRecruitment {
		
		
		
	}

	message _BeyondRoomInvitation {
		
		
		
		
		
	}

	message _BeyondGachaGift {
		
	}

	message _BeyondCostumeShareCode {
		
	}

	message _HallRecruitingInvitation {
		repeated 
		
		
		
		
		
	}

	
	
	
	
	
	
	
	
	
	oneof HGIIOKKHLPF {
		
		
	}
	oneof content {
		
		_BeyondTeamInvitation beyond_team_invitation = 1794;
		_BeyondCollectionNewCaptain beyond_collection_new_captain = 1401;
		_BeyondRoomInvitation beyond_room_invitation = 1789;
		_HallInvitation hall_invitation = 1160;
		_BeyondCostumeShareCode beyond_costume_share_code = 1404;
		_HallRecruitingInvitation hall_recruiting_invitation = 1075;
		
		_BeyondTeamRecruitment beyond_team_recruitment = 1990;
		_BeyondTeamApplication beyond_team_application = 714;
		
		SystemHint system_hint = 1928;
	}
}