syntax = "proto3";

enum ClientPlayType {
	_CLIENT_PLAY_TYPE_CLIENT_PLAY_NONE_TYPE = 0;
	_CLIENT_PLAY_TYPE_CLIENT_PLAY_FILMFEST_SHOOTING_TYPE = 1;
	_CLIENT_PLAY_TYPE_CLIENT_PLAY_COOK_GAME_TYPE = 2;
	_CLIENT_PLAY_TYPE_CLIENT_PLAY_LAN_V4_PUSH_BOX_TYPE = 3;
	_CLIENT_PLAY_TYPE_CLIENT_PLAY_CATCAFE_LAYOUT_TYPE = 4;
	_CLIENT_PLAY_TYPE_CLIENT_PLAY_CATCAFE_CAT_TYPE = 5;
	_CLIENT_PLAY_TYPE_CLIENT_PLAY_GREAT_FESTIVAL_V2_SHEET_RESTORE_TYPE = 6;
	_CLIENT_PLAY_TYPE_CLIENT_PLAY_BIRD_BALL_TYPE = 7;
	_CLIENT_PLAY_TYPE_CLIENT_PLAY_FAIRY_TALES_FLYPPY_HAT_TOY_TYPE = 8;
	_CLIENT_PLAY_TYPE_CLIENT_PLAY_NAHIDA_BIRTH_FLOAT_TOY_TYPE = 9;
	_CLIENT_PLAY_TYPE_CLIENT_PLAY_CEREMONY_DOODLE_TYPE = 10;
	_CLIENT_PLAY_TYPE_CLIENT_PLAY_LAN_V5_CARD_TYPE = 12;
	_CLIENT_PLAY_TYPE_CLIENT_PLAY_LAN_V5_CARD_NPC_LEVEL_TYPE = 13;
	_CLIENT_PLAY_TYPE_CLIENT_PLAY_DREAM_SWITCHING = 14;
	_CLIENT_PLAY_TYPE_CLIENT_PLAY_NATLAN_DRILL_COLLECT = 15;
	_CLIENT_PLAY_TYPE_CLIENT_PLAY_HOLIDAY_RESORT_ADVENTURE = 16;
	_CLIENT_PLAY_TYPE_CLIENT_PLAY_AUTOCHESS_FRUIT_PICK = 17;
	_CLIENT_PLAY_TYPE_CLIENT_PLAY_LAN_V6_DANMAKU = 18;
	_CLIENT_PLAY_TYPE_CLIENT_PLAY_PAINTING_REPAIR_V2 = 19;
	_CLIENT_PLAY_TYPE_CLIENT_PLAY_LOLI_JUMP = 20;
}
