syntax = "proto3";

enum CMKADHFAEJC {
	CMKADHFAEJC_NONE = 0;
	CMKADHFAEJC_ENTITY = 1;
	CMKADHFAEJC_GUID = 2;
	CMKADHFAEJC_INT_32 = 3;
	CMKADHFAEJC_BOOL = 4;
	CMKADHFAEJC_FLOAT = 5;
	CMKADHFAEJC_STRING = 6;
	CMKADHFAEJC_GUID_LIST = 7;
	CMKADHFAEJC_INT_32_LIST = 8;
	CMKADHFAEJC_BOOL_LIST = 9;
	CMKADHFAEJC_FLOAT_LIST = 10;
	CMKADHFAEJC_STRING_LIST = 11;
	CMKADHFAEJC_VECTOR_3 = 12;
	CMKADHFAEJC_ENTITY_LIST = 13;
	CMKADHFAEJC_ENUM = 14;
	CMKADHFAEJC_VECTOR_3_LIST = 15;
	CMKADHFAEJC_VARIABLE = 16;
	CMKADHFAEJC_ARMY = 17;
	CMKADHFAEJC_COMP_TYPE = 18;
	CMKADHFAEJC_CATEGORY_TYPE = 19;
	CMKADHFAEJC_CONFIG_REFERENCE = 20;
	CMKADHFAEJC_ENTITY_REFERENCE = 21;
	CMKADHFAEJC_CONFIG_REFERENCE_LIST = 22;
	CMKADHFAEJC_ENTITY_REFERENCE_LIST = 23;
	CMKADHFAEJC_ARMY_LIST = 24;
	CMKADHFAEJC_STRUCT = 25;
	CMKADHFAEJC_STRUCT_LIST = 26;
	CMKADHFAEJC_DICT = 27;
	CMKADHFAEJC_CUSTOM_VALUE_SNAPSHOT = 28;
	CMKADHFAEJC_ENUM_LIST = 29;
	CMKADHFAEJC_MAX = 50;
}
