syntax = "proto3";

import "CoopCg.proto";
import "CoopPoint.proto";
import "CoopReward.proto";

message CoopChapter {
	enum State {
		STATE_CLOSE = 0;
		STATE_COND_NOT_MEET = 1;
		STATE_COND_MEET = 2;
		STATE_ACCEPT = 3;
	}

	repeated uint32 lock_reason_list = 14;
	repeated uint32 DNEDOKHNKCF = 13;
	repeated uint32 AIMPAEMAFBG = 12;
	repeated CoopPoint coop_point_list = 11;
	repeated CoopCg coop_cg_list = 4;
	repeated CoopReward coop_reward_list = 10;
	map<uint32, uint32> seen_ending_map = 5;
	uint32 total_end_count = 2;
	uint32 finished_end_count = 9;
	State state = 15;
	uint32 id = 3;
}
