syntax = "proto3";

import "ChallengeFinishType.proto";
import "ChannellerSlabLoopDungeonResultInfo.proto";
import "CustomDungeonResultInfo.proto";
import "EffigyChallengeDungeonResultInfo.proto";
import "PotionDungeonResultInfo.proto";

message DungeonChallengeFinishNotify {
	map<uint32, StrengthenPointData> strengthen_point_data_map = 6;
	
	
	
	
	
	
	ChallengeFinishType finish_type = 5;
	oneof detail {
		PotionDungeonResultInfo potion_dungeon_result_info = 958;
		EffigyChallengeDungeonResultInfo effigy_challenge_dungeon_result_info = 967;
		ChannellerSlabLoopDungeonResultInfo channeller_slab_loop_dungeon_result_info = 1552;
		CustomDungeonResultInfo custom_dungeon_result_info = 1769;
	}
}