syntax = "proto3";


import "_ChangeHpDebtsReason.proto";
import "ChangeEnergyReason.proto";
import "ChangHpReason.proto";
import "FCMFLCPEGHO.proto";
import "PropChangeReason.proto";

message EntityFightPropChangeReasonNotify {
	repeated uint32 param_list = 12;
	FCMFLCPEGHO detail_info = 6;
	uint32 entity_id = 11;
	_ChangeHpDebtsReason _change_hp_debts_reason = 13;
	uint32 LJFGBOOMIPP = 2;
	float prop_delta = 3;
	uint32 prop_type = 14;
	PropChangeReason reason = 5;
	float BJLOMIGAOFH = 7;
	ChangHpReason change_hp_reason = 8;
	ChangeEnergyReason change_energy_reson = 15;
}
