syntax = "proto3";

enum FeatureBlockType {
	FEATURE_BLOCK_TYPE_NONE = 0;
	FEATURE_BLOCK_TYPE_CHAT = 1;
	FEATURE_BLOCK_TYPE_MP = 2;
	FEATURE_BLOCK_TYPE_FEATRURE_BLOCK_TYPE_CRC = 3;
	FEATURE_BLOCK_TYPE_HOME = 4;
	FEATURE_BLOCK_TYPE_HALL_CUSTOME = 5;
	FEATURE_BLOCK_TYPE_BEYOND = 6;
	FEATURE_BLOCK_TYPE_BEYOND_MP = 7;
	FEATURE_BLOCK_TYPE_BEYOND_DISPLAY_COSTUME = 8;
	FEATURE_BLOCK_TYPE_BEYOND_UPDATE_COSTUME = 9;
	FEATURE_BLOCK_TYPE_BEYOND_ARCHIVE = 10;
	FEATURE_BLOCK_TYPE_BEYOND_ROOM = 11;
	FEATURE_BLOCK_TYPE_BEYOND_GACHA_GIFT = 12;
	FEATURE_BLOCK_TYPE_BEYOND_SHOP_GIFT = 13;
	FEATURE_BLOCK_TYPE_BEYOND_VOICE_CHAT = 14;
}
