syntax = "proto3";

import "GachaUpInfo.proto";

message GachaInfo {
	repeated uint32 display_up5_item_list = 1802;
	repeated GachaUpInfo gacha_up_info_list = 593;
	string LOBIEKALOEM = 11;
	repeated uint32 display_up4_item_list = 323;
	string title_textmap = 149;
	repeated uint32 AFBKFLFOGMF = 1652;
	string gacha_preview_prefab_path = 14;
	string gacha_prefab_path = 3;
	string DGOIEHCEBFM = 12;
	string LCNBNGKMEFE = 1241;
	string OEIKDNCFFKG = 1845;
	uint32 end_time = 2;
	uint32 left_gacha_times = 4;
	uint32 gacha_times_limit = 13;
	bool KHANMGINCMP = 769;
	bool PGNMPDKFCKE = 1554;
	uint32 gacha_sort_id = 1;
	uint32 PHAOAGHODPN = 980;
	uint32 IICCKKMBIIN = 7;
	uint32 wish_max_progress = 1905;
	uint32 wish_progress = 514;
	uint32 schedule_id = 5;
	uint32 cost_item_num = 6;
	uint32 KIPDIEOHELN = 9;
	uint32 begin_time = 8;
	uint32 gacha_type = 10;
	uint32 wish_item_id = 973;
	uint32 ten_cost_item_num = 15;
}