syntax = "proto3";

import "JCMNIEIECKL.proto";
import "ProfilePicture.proto";
import "Vector.proto";

message HPLBIFMGAEC {
	Vector NONNNDNMOID = 6;
	string nick_name = 14;
	string online_id = 15;
	repeated Uint32Pair KBMKGPBDHNE = 4;
	ProfilePicture profile_picture = 1;
	repeated JCMNIEIECKL HGFNJMLLECI = 10;
	string HADOFGGLMDB = 3;
	repeated JCMNIEIECKL BKMJBFKLODL = 11;
	uint32 uid = 7;
	uint32 finish_time = 9;
	uint32 PODGBNLNDIE = 2;
	uint32 progress = 12;
	uint32 CJHCHMAECBC = 8;
	uint32 score = 13;
}
