syntax = "proto3";

enum IOLKHFCLGFP {
	IOLKHFCLGFP_BEYOND_ENUM_NONE = 0;
	IOLKHFCLGFP_BEYOND_COMPARE_OPERATOR_EQUAL = 100;
	IOLKHFCLGFP_BEYOND_COMPARE_OPERATOR_LESS = 101;
	IOLKHFCLGFP_BEYOND_COMPARE_OPERATOR_LESS_EQUAL = 102;
	IOLKHFCLGFP_BEYOND_COMPARE_OPERATOR_GREATER = 103;
	IOLKHFCLGFP_BEYOND_COMPARE_OPERATOR_GREATER_EQUAL = 104;
	IOLKHFCLGFP_BEYOND_COMPARE_OPERATOR_NOT_EQUAL = 105;
	IOLKHFCLGFP_BEYOND_LOGIC_OPERATOR_AND = 200;
	IOLKHFCLGFP_BEYOND_LOGIC_OPERATOR_OR = 201;
	IOLKHFCLGFP_BEYOND_LOGIC_OPERATOR_XOR = 202;
	IOLKHFCLGFP_BEYOND_LOGIC_OPERATOR_NOT = 203;
	IOLKHFCLGFP_BEYOND_NUMERICAL_OPERATOR_ADD = 300;
	IOLKHFCLGFP_BEYOND_NUMERICAL_OPERATOR_SUBTRACT = 301;
	IOLKHFCLGFP_BEYOND_NUMERICAL_OPERATOR_MULTIPLY = 302;
	IOLKHFCLGFP_BEYOND_NUMERICAL_OPERATOR_DIVID = 303;
	IOLKHFCLGFP_BEYOND_NUMERICAL_OPERATOR_MODULO = 304;
	IOLKHFCLGFP_BEYOND_NUMERICAL_OPERATOR_POWER = 305;
	IOLKHFCLGFP_BEYOND_NUMERICAL_OPERATOR_MAX = 306;
	IOLKHFCLGFP_BEYOND_NUMERICAL_OPERATOR_MIN = 307;
	IOLKHFCLGFP_BEYOND_NUMERICAL_OPERATOR_LOG = 308;
	IOLKHFCLGFP_BEYOND_NUMERICAL_OPERATOR_ABS = 309;
	IOLKHFCLGFP_BEYOND_NUMERICAL_OPERATOR_SIGN = 310;
	IOLKHFCLGFP_BEYOND_NUMERICAL_OPERATOR_SQRT = 311;
	IOLKHFCLGFP_BEYOND_NUMERICAL_OPERATOR_CLAMP = 312;
	IOLKHFCLGFP_BEYOND_ATTACK_SHAPE_BOX = 400;
	IOLKHFCLGFP_BEYOND_ATTACK_SHAPE_SPHERE = 401;
	IOLKHFCLGFP_BEYOND_ATTACK_SHAPE_CIRCLE = 402;
	IOLKHFCLGFP_BEYOND_CIRCLE_DETECT_DIRECTION_CENTER_TO_SIDE = 450;
	IOLKHFCLGFP_BEYOND_CIRCLE_DETECT_DIRECTION_CLOCKWISE = 451;
	IOLKHFCLGFP_BEYOND_CIRCLE_DETECT_DIRECTION_COUNTERCLOCKWISE = 452;
	IOLKHFCLGFP_BEYOND_ENTITY_LIFE_STATE_LIVE = 500;
	IOLKHFCLGFP_BEYOND_ENTITY_LIFE_STATE_DEAD = 501;
	IOLKHFCLGFP_BEYOND_ORDER_RULE_ASCENDING = 600;
	IOLKHFCLGFP_BEYOND_ORDER_RULE_DESCENDING = 601;
	IOLKHFCLGFP_BEYOND_ORDER_RULE_RANDOM = 602;
	IOLKHFCLGFP_BEYOND_ROUND_RULE_CEILING = 700;
	IOLKHFCLGFP_BEYOND_ROUND_RULE_FLOOR = 701;
	IOLKHFCLGFP_BEYOND_ROUND_RULE_ROUND = 702;
	IOLKHFCLGFP_BEYOND_ROUND_RULE_TRUNCATE = 703;
	IOLKHFCLGFP_BEYOND_CONVERTOR_INT_32_BOOL = 800;
	IOLKHFCLGFP_BEYOND_CONVERTOR_INT_32_FLOAT = 801;
	IOLKHFCLGFP_BEYOND_CONVERTOR_INT_32_STRING = 802;
	IOLKHFCLGFP_BEYOND_CONVERTOR_ENTITY_STRING = 803;
	IOLKHFCLGFP_BEYOND_CONVERTOR_GUID_STRING = 804;
	IOLKHFCLGFP_BEYOND_CONVERTOR_BOOL_INT_32 = 805;
	IOLKHFCLGFP_BEYOND_CONVERTOR_BOOL_STRING = 806;
	IOLKHFCLGFP_BEYOND_CONVERTOR_FLOAT_INT_32 = 807;
	IOLKHFCLGFP_BEYOND_CONVERTOR_FLOAT_STRING = 808;
	IOLKHFCLGFP_BEYOND_CONVERTOR_VECTOR_3_STRING = 809;
	IOLKHFCLGFP_BEYOND_CONVERTOR_ARMY_STRING = 810;
	IOLKHFCLGFP_BEYOND_ENTITY_POINT_TYPE_VECTOR = 900;
	IOLKHFCLGFP_BEYOND_ENTITY_POINT_TYPE_CURVE = 901;
	IOLKHFCLGFP_BEYOND_ENTITY_MOVE_TYPE_ONEWAY = 1000;
	IOLKHFCLGFP_BEYOND_ENTITY_MOVE_TYPE_RECIPROCATE = 1001;
	IOLKHFCLGFP_BEYOND_ENTITY_MOVE_TYPE_LOOP = 1002;
	IOLKHFCLGFP_BEYOND_FOLLOW_TYPE_DEFAULT = 1100;
	IOLKHFCLGFP_BEYOND_FOLLOW_TYPE_POS = 1101;
	IOLKHFCLGFP_BEYOND_FOLLOW_TYPE_ROT = 1102;
	IOLKHFCLGFP_BEYOND_FOLLOW_COORDINATE_RELATIVE = 1200;
	IOLKHFCLGFP_BEYOND_FOLLOW_COORDINATE_ABSOLUTE = 1201;
	IOLKHFCLGFP_BEYOND_ELEMENT_TYPE_NONE = 1300;
	IOLKHFCLGFP_BEYOND_ELEMENT_TYPE_FIRE = 1301;
	IOLKHFCLGFP_BEYOND_ELEMENT_TYPE_WATER = 1302;
	IOLKHFCLGFP_BEYOND_ELEMENT_TYPE_WIND = 1303;
	IOLKHFCLGFP_BEYOND_ELEMENT_TYPE_THUNDER = 1304;
	IOLKHFCLGFP_BEYOND_ELEMENT_TYPE_GRASS = 1305;
	IOLKHFCLGFP_BEYOND_ELEMENT_TYPE_ICE = 1306;
	IOLKHFCLGFP_BEYOND_ELEMENT_TYPE_ROCK = 1307;
	IOLKHFCLGFP_BEYOND_ENTITY_TYPE_LEVEL = 1401;
	IOLKHFCLGFP_BEYOND_ENTITY_TYPE_GADGET = 1402;
	IOLKHFCLGFP_BEYOND_ENTITY_TYPE_PLAYER = 1403;
	IOLKHFCLGFP_BEYOND_ENTITY_TYPE_AVATAR = 1404;
	IOLKHFCLGFP_BEYOND_ENTITY_TYPE_MONSTER = 1405;
	IOLKHFCLGFP_BEYOND_ROLE_STATUS_REASON_ADD_FAILED_EXCEPTION = 1500;
	IOLKHFCLGFP_BEYOND_ROLE_STATUS_REASON_ADD_FAILED_RESISTED = 1501;
	IOLKHFCLGFP_BEYOND_ROLE_STATUS_REASON_ADD_FAILED_OVERSLOTS = 1502;
	IOLKHFCLGFP_BEYOND_ROLE_STATUS_REASON_ADD_FAILED_OVERCOUNT = 1503;
	IOLKHFCLGFP_BEYOND_ROLE_STATUS_REASON_ADD_SUCC_NEW_SLOT = 1504;
	IOLKHFCLGFP_BEYOND_ROLE_STATUS_REASON_ADD_SUCC_UPDATE = 1505;
	IOLKHFCLGFP_BEYOND_ROLE_STATUS_REASON_REMOVE_SLOT_REPLACED = 1506;
	IOLKHFCLGFP_BEYOND_ROLE_STATUS_REASON_REMOVE_LIFE_END = 1507;
	IOLKHFCLGFP_BEYOND_ROLE_STATUS_REASON_REMOVE_DISPERSE = 1508;
	IOLKHFCLGFP_BEYOND_ROLE_STATUS_REASON_REMOVE_CANCEL = 1509;
	IOLKHFCLGFP_BEYOND_ROLE_STATUS_REASON_REMOVE_DUTY_CHANGE = 1510;
	IOLKHFCLGFP_BEYOND_ROLE_STATUS_REASON_REMOVE_AFFIX_DEACTIVE = 1511;
	IOLKHFCLGFP_BEYOND_ROLE_STATUS_REASON_REMOVE_SHIELD_BREAK = 1512;
	IOLKHFCLGFP_BEYOND_ROLE_STATUS_REMOVE_POLICY_ALL = 1540;
	IOLKHFCLGFP_BEYOND_ROLE_STATUS_REMOVE_POLICY_SINGLE = 1541;
	IOLKHFCLGFP_BEYOND_REVIVE_POINT_SELECT_POLICY_NEAREST = 1601;
	IOLKHFCLGFP_BEYOND_REVIVE_POINT_SELECT_POLICY_LAST_ACTIVE = 1602;
	IOLKHFCLGFP_BEYOND_REVIVE_POINT_SELECT_POLICY_PRIORITY = 1603;
	IOLKHFCLGFP_BEYOND_REVIVE_POINT_SELECT_POLICY_RANDOM = 1604;
	IOLKHFCLGFP_BEYOND_DIE_REASON_BEYOND_BLUEPRINT = 1605;
	IOLKHFCLGFP_BEYOND_DIE_REASON_NORMAL = 1606;
	IOLKHFCLGFP_BEYOND_DIE_REASON_SPECIAL = 1607;
	IOLKHFCLGFP_BEYOND_TRIGONOMETRIC_OP_CAL_COS = 1700;
	IOLKHFCLGFP_BEYOND_TRIGONOMETRIC_OP_CAL_SIN = 1701;
	IOLKHFCLGFP_BEYOND_TRIGONOMETRIC_OP_CAL_TAN = 1702;
	IOLKHFCLGFP_BEYOND_TRIGONOMETRIC_OP_CAL_ACOS = 1703;
	IOLKHFCLGFP_BEYOND_TRIGONOMETRIC_OP_CAL_ASIN = 1704;
	IOLKHFCLGFP_BEYOND_TRIGONOMETRIC_OP_CAL_ATAN = 1705;
	IOLKHFCLGFP_BEYOND_TRIGONOMETRIC_OP_CAL_RAD_2_DAG = 1706;
	IOLKHFCLGFP_BEYOND_TRIGONOMETRIC_OP_CAL_DAG_2_RAD = 1707;
	IOLKHFCLGFP_BEYOND_AVATAR_DISTURBER_TRAVELLER = 1800;
	IOLKHFCLGFP_BEYOND_AVATAR_DISTURBER_FIELD = 1801;
	IOLKHFCLGFP_BEYOND_AVATAR_DISTURBER_EJECT = 1802;
	IOLKHFCLGFP_BEYOND_AVATAR_DISTURBER_DRAG = 1803;
	IOLKHFCLGFP_BEYOND_AVATAR_DISTURBER_RADIATE = 1810;
	IOLKHFCLGFP_BEYOND_AVATAR_DISTURBER_SINGLE_DIR = 1811;
	IOLKHFCLGFP_BEYOND_UI_SWITCH_STATUS_OFF = 1900;
	IOLKHFCLGFP_BEYOND_UI_SWITCH_STATUS_ON = 1901;
	IOLKHFCLGFP_BEYOND_UI_SWITCH_STATUS_HIDE = 1902;
	IOLKHFCLGFP_BEYOND_MP_ACTION_TARGET_TYPE_NONE = 2000;
	IOLKHFCLGFP_BEYOND_MP_ACTION_TARGET_TYPE_ALIANCE = 2001;
	IOLKHFCLGFP_BEYOND_MP_ACTION_TARGET_TYPE_ENEMY = 2002;
	IOLKHFCLGFP_BEYOND_MP_ACTION_TARGET_TYPE_SELF = 2003;
	IOLKHFCLGFP_BEYOND_MP_ACTION_TARGET_TYPE_SELF_CAMP = 2004;
	IOLKHFCLGFP_BEYOND_MP_ACTION_TARGET_TYPE_ALL = 2005;
	IOLKHFCLGFP_BEYOND_MP_ACTION_TARGET_TYPE_ALL_EXCEPT_SELF = 2006;
	IOLKHFCLGFP_BEYOND_MP_ACTION_TARGET_TYPE_ALLIANCE_INCLUDE_SELF = 2007;
	IOLKHFCLGFP_BEYOND_HIT_DETECTION_TRIGGER_NONE = 2100;
	IOLKHFCLGFP_BEYOND_HIT_DETECTION_TRIGGER_ONCE = 2101;
	IOLKHFCLGFP_BEYOND_HIT_DETECTION_TRIGGER_NO_REPEAT = 2102;
	IOLKHFCLGFP_BEYOND_HIT_DETECTION_TRIGGER_ALWAYS = 2103;
	IOLKHFCLGFP_BEYOND_STRIKE_TYPE_NONE = 2200;
	IOLKHFCLGFP_BEYOND_STRIKE_TYPE_DEFAULT = 2201;
	IOLKHFCLGFP_BEYOND_STRIKE_TYPE_SLASH = 2202;
	IOLKHFCLGFP_BEYOND_STRIKE_TYPE_BLUNT = 2203;
	IOLKHFCLGFP_BEYOND_STRIKE_TYPE_PIERCE = 2204;
	IOLKHFCLGFP_BEYOND_STRIKE_TYPE_SPEAR = 2205;
	IOLKHFCLGFP_BEYOND_ATTACK_TYPE_NONE = 2300;
	IOLKHFCLGFP_BEYOND_ATTACK_TYPE_MELEE = 2301;
	IOLKHFCLGFP_BEYOND_ATTACK_TYPE_RANGE = 2302;
	IOLKHFCLGFP_BEYOND_ATTACK_TYPE_DEFAULT = 2303;
	IOLKHFCLGFP_BEYOND_HIT_IMPULSE_TYPE_DEFAULT = 2400;
	IOLKHFCLGFP_BEYOND_HIT_IMPULSE_TYPE_LV_0 = 2401;
	IOLKHFCLGFP_BEYOND_HIT_IMPULSE_TYPE_LV_1 = 2402;
	IOLKHFCLGFP_BEYOND_HIT_IMPULSE_TYPE_LV_2 = 2403;
	IOLKHFCLGFP_BEYOND_HIT_IMPULSE_TYPE_LV_3 = 2404;
	IOLKHFCLGFP_BEYOND_HIT_IMPULSE_TYPE_LV_4 = 2405;
	IOLKHFCLGFP_BEYOND_HIT_IMPULSE_TYPE_LV_5 = 2406;
	IOLKHFCLGFP_BEYOND_HIT_IMPULSE_TYPE_LV_6 = 2407;
	IOLKHFCLGFP_BEYOND_HIT_IMPULSE_TYPE_LV_7 = 2408;
	IOLKHFCLGFP_BEYOND_HIT_IMPULSE_TYPE_LV_8 = 2409;
	IOLKHFCLGFP_BEYOND_HIT_IMPULSE_TYPE_LV_9 = 2410;
	IOLKHFCLGFP_BEYOND_RETREAT_TYPE_NONE = 2500;
	IOLKHFCLGFP_BEYOND_RETREAT_TYPE_BY_ATTACKER = 2501;
	IOLKHFCLGFP_BEYOND_RETREAT_TYPE_BY_HIT_DIRECTION = 2502;
	IOLKHFCLGFP_BEYOND_RETREAT_TYPE_BY_ORIGINAL_OWNER = 2503;
	IOLKHFCLGFP_BEYOND_RETREAT_TYPE_BY_TANGENT = 2504;
	IOLKHFCLGFP_BEYOND_RETREAT_TYPE_BY_HIT_DIRECTION_INVERSE = 2505;
	IOLKHFCLGFP_BEYOND_RETREAT_TYPE_BY_ATTACKER_FORWARD = 2506;
	IOLKHFCLGFP_BEYOND_RETREAT_TYPE_BY_ATTACKER_INVERSE = 2507;
	IOLKHFCLGFP_BEYOND_CHECK_HIT_LAYER_TYPE_NONE = 2600;
	IOLKHFCLGFP_BEYOND_CHECK_HIT_LAYER_TYPE_ONLY_HITBOX = 2601;
	IOLKHFCLGFP_BEYOND_CHECK_HIT_LAYER_TYPE_ONLY_SCENE = 2602;
	IOLKHFCLGFP_BEYOND_CHECK_HIT_LAYER_TYPE_ONLY_MASSIVE = 2603;
	IOLKHFCLGFP_BEYOND_CHECK_HIT_LAYER_TYPE_ALL = 2604;
	IOLKHFCLGFP_BEYOND_CHECK_HIT_LAYER_TYPE_GADGET_COLLIDER = 2605;
	IOLKHFCLGFP_BEYOND_VELOCITY_FORCE_TYPE_RETREAT_TYPE = 2700;
	IOLKHFCLGFP_BEYOND_VELOCITY_FORCE_TYPE_RETREAT_AIR_TYPE = 2701;
	IOLKHFCLGFP_BEYOND_VELOCITY_FORCE_TYPE_RUSH_MOVE_TYPE = 2702;
	IOLKHFCLGFP_BEYOND_VELOCITY_FORCE_TYPE_WIND_ZONE_TYPE = 2703;
	IOLKHFCLGFP_BEYOND_VELOCITY_FORCE_TYPE_AIR_FLOW_TYPE = 2704;
	IOLKHFCLGFP_BEYOND_VELOCITY_FORCE_TYPE_RISE_TYPE = 2705;
	IOLKHFCLGFP_BEYOND_VELOCITY_FORCE_TYPE_SPEED_UP_TYPE = 2706;
	IOLKHFCLGFP_BEYOND_VELOCITY_FORCE_TYPE_AIRFLOW_ACC_TYPE = 2707;
	IOLKHFCLGFP_BEYOND_VELOCITY_FORCE_TYPE_INERTIA_TYPE = 2708;
	IOLKHFCLGFP_BEYOND_VELOCITY_FORCE_TYPE_FIXED_RUSH_MOVE_TYPE = 2709;
	IOLKHFCLGFP_BEYOND_VELOCITY_FORCE_TYPE_LIGHT_CORE_TYPE_NORMAL = 2710;
	IOLKHFCLGFP_BEYOND_VELOCITY_FORCE_TYPE_LIGHT_CORE_TYPE_ACCELERATE = 2711;
	IOLKHFCLGFP_BEYOND_VELOCITY_FORCE_TYPE_GOROU_ZONE_TYPE = 2712;
	IOLKHFCLGFP_BEYOND_VELOCITY_FORCE_TYPE_UGC_DIRECTED_FORCE_TYPE = 2713;
	IOLKHFCLGFP_BEYOND_VELOCITY_FORCE_TYPE_TRAMPOLINE_FORCE_TYPE = 2714;
	IOLKHFCLGFP_BEYOND_VELOCITY_FORCE_TYPE_GRAPPLING_HOOK_MOVE_TYPE = 2715;
	IOLKHFCLGFP_BEYOND_VELOCITY_FORCE_TYPE_WIDGET_AIRFLOW_TYPE = 2716;
	IOLKHFCLGFP_BEYOND_VELOCITY_FORCE_TYPE_LINEAR_ATTENUATION_IGNORE_AIR_G_TYPE = 2717;
	IOLKHFCLGFP_BEYOND_VELOCITY_FORCE_TYPE_BEYOND_TYPE = 2718;
	IOLKHFCLGFP_BEYOND_VELOCITY_FORCE_TYPE_BEYOND_FORCE_FIELD_TYPE = 2719;
	IOLKHFCLGFP_BEYOND_VELOCITY_FORCE_TYPE_BEYOND_EJECT_TYPE = 2720;
	IOLKHFCLGFP_BEYOND_VELOCITY_FORCE_TYPE_BEYOND_DRAG_TYPE = 2721;
	IOLKHFCLGFP_BEYOND_CUSTOM_SKILL_MOVE_TYPE_COMBAT_SKILL_MOVE = 2800;
	IOLKHFCLGFP_BEYOND_CUSTOM_SKILL_MOVE_TYPE_COMBAT_AIR = 2801;
	IOLKHFCLGFP_BEYOND_CUSTOM_SKILL_SLOT_VISIBLE_TYPE_SHOW = 2802;
	IOLKHFCLGFP_BEYOND_CUSTOM_SKILL_SLOT_VISIBLE_TYPE_HIDE = 2803;
	IOLKHFCLGFP_BEYOND_CUSTOM_SKILL_INTERVAL_MODE_CLOSED = 2804;
	IOLKHFCLGFP_BEYOND_CUSTOM_SKILL_INTERVAL_MODE_OPEN = 2805;
	IOLKHFCLGFP_BEYOND_CUSTOM_SKILL_INTERVAL_MODE_OPEN_CLOSED = 2806;
	IOLKHFCLGFP_BEYOND_CUSTOM_SKILL_INTERVAL_MODE_CLOSED_OPEN = 2807;
	IOLKHFCLGFP_BEYOND_CUSTOM_SKILL_SLOT_STACK_TOP_HANDLE_TYPE_DESTROY = 2810;
	IOLKHFCLGFP_BEYOND_CUSTOM_SKILL_SLOT_STACK_TOP_HANDLE_TYPE_KEEP = 2811;
	IOLKHFCLGFP_BEYOND_CUSTOM_SKILL_SLOT_STACK_TOP_HANDLE_TYPE_UNBIND = 2812;
	IOLKHFCLGFP_BEYOND_CUSTOM_SKILL_SLOT_DUTY_CHANGE_HANDLE_TYPE_DESTROY = 2820;
	IOLKHFCLGFP_BEYOND_CUSTOM_SKILL_SLOT_DUTY_CHANGE_HANDLE_TYPE_KEEP = 2821;
	IOLKHFCLGFP_BEYOND_TURNMODE_PREFER_TARGET_TO_INPUT = 2900;
	IOLKHFCLGFP_BEYOND_TURNMODE_ONLY_INPUT = 2901;
	IOLKHFCLGFP_BEYOND_TURNMODE_ONLY_TARGET = 2902;
	IOLKHFCLGFP_BEYOND_TURNMODE_PREFER_TARGET_TO_CAMERA = 2903;
	IOLKHFCLGFP_BEYOND_TURNMODE_ONLY_CAMERA = 2904;
	IOLKHFCLGFP_BEYOND_TURNMODE_PREFER_INPUT_TO_TARGET = 2905;
	IOLKHFCLGFP_BEYOND_BORN_TYPE_SELF = 3000;
	IOLKHFCLGFP_BEYOND_BORN_TYPE_BORN_BY_COLLISION_POINT = 3001;
	IOLKHFCLGFP_BEYOND_CUSTOM_SKILL_SLOT_TYPE_ATTACK = 3100;
	IOLKHFCLGFP_BEYOND_CUSTOM_SKILL_SLOT_TYPE_SKILL_1 = 3101;
	IOLKHFCLGFP_BEYOND_CUSTOM_SKILL_SLOT_TYPE_SKILL_2 = 3102;
	IOLKHFCLGFP_BEYOND_CUSTOM_SKILL_SLOT_TYPE_SKILL_3 = 3103;
	IOLKHFCLGFP_BEYOND_CUSTOM_SKILL_SLOT_TYPE_SKILL_4 = 3104;
	IOLKHFCLGFP_BEYOND_CUSTOM_SKILL_SLOT_TYPE_SKILL_11 = 3111;
	IOLKHFCLGFP_BEYOND_CUSTOM_SKILL_SLOT_TYPE_SKILL_12 = 3112;
	IOLKHFCLGFP_BEYOND_CUSTOM_SKILL_SLOT_TYPE_SKILL_13 = 3113;
	IOLKHFCLGFP_BEYOND_CUSTOM_SKILL_SLOT_TYPE_SKILL_14 = 3114;
	IOLKHFCLGFP_BEYOND_CUSTOM_SKILL_SLOT_TYPE_SKILL_21 = 3121;
	IOLKHFCLGFP_BEYOND_CUSTOM_SKILL_SLOT_TYPE_SKILL_22 = 3122;
	IOLKHFCLGFP_BEYOND_CUSTOM_SKILL_SLOT_TYPE_SKILL_23 = 3123;
	IOLKHFCLGFP_BEYOND_CUSTOM_SKILL_SLOT_TYPE_SKILL_24 = 3124;
	IOLKHFCLGFP_BEYOND_CUSTOM_SKILL_SLOT_TYPE_SKILL_25 = 3125;
	IOLKHFCLGFP_BEYOND_CUSTOM_SKILL_SLOT_TYPE_SKILL_26 = 3126;
	IOLKHFCLGFP_BEYOND_CUSTOM_SKILL_SLOT_TYPE_SKILL_27 = 3127;
	IOLKHFCLGFP_BEYOND_CUSTOM_SKILL_SLOT_TYPE_SKILL_28 = 3128;
	IOLKHFCLGFP_BEYOND_CUSTOM_SKILL_SLOT_TYPE_SKILL_29 = 3129;
	IOLKHFCLGFP_BEYOND_CUSTOM_SKILL_SLOT_TYPE_SKILL_30 = 3130;
	IOLKHFCLGFP_BEYOND_CUSTOM_SKILL_SLOT_TYPE_SKILL_31 = 3131;
	IOLKHFCLGFP_BEYOND_CUSTOM_SKILL_SLOT_TYPE_SKILL_32 = 3132;
	IOLKHFCLGFP_BEYOND_CUSTOM_SKILL_SLOT_TYPE_SKILL_33 = 3133;
	IOLKHFCLGFP_BEYOND_CUSTOM_SKILL_SLOT_TYPE_SKILL_34 = 3134;
	IOLKHFCLGFP_BEYOND_CUSTOM_SKILL_SLOT_TYPE_SKILL_35 = 3135;
	IOLKHFCLGFP_BEYOND_ENMITY_TRACE_TYPE_SELF = 3200;
	IOLKHFCLGFP_BEYOND_ENMITY_TRACE_TYPE_OWNER = 3201;
	IOLKHFCLGFP_BEYOND_ENMITY_TRACE_TYPE_TOP_OWNER = 3202;
	IOLKHFCLGFP_BEYOND_AI_THREAT_LEVEL_UNAWARE = 3300;
	IOLKHFCLGFP_BEYOND_AI_THREAT_LEVEL_AWARE = 3301;
	IOLKHFCLGFP_BEYOND_AI_THREAT_LEVEL_ALERT = 3302;
	IOLKHFCLGFP_BEYOND_ATTENUATION_CURVE_TYPE_LINEAR = 3400;
	IOLKHFCLGFP_BEYOND_ATTENUATION_CURVE_TYPE_EASE_OUT = 3401;
	IOLKHFCLGFP_BEYOND_ATTENUATION_CURVE_TYPE_EASE_IN = 3402;
	IOLKHFCLGFP_BEYOND_POP_UP_FINISH_TYPE_DEFAULT = 3500;
	IOLKHFCLGFP_BEYOND_POP_UP_FINISH_TYPE_TIME_OUT = 3501;
	IOLKHFCLGFP_BEYOND_POP_UP_FINISH_TYPE_REFRESH_ACT = 3502;
	IOLKHFCLGFP_BEYOND_POP_UP_FINISH_TYPE_REFRESH_ALL = 3503;
	IOLKHFCLGFP_BEYOND_POP_UP_FINISH_TYPE_CLOSE_ACT = 3504;
	IOLKHFCLGFP_BEYOND_POP_UP_FINISH_TYPE_CLOSE_BP = 3505;
	IOLKHFCLGFP_BEYOND_POP_UP_REFRESH_TYPE_NONE = 3510;
	IOLKHFCLGFP_BEYOND_POP_UP_REFRESH_TYPE_PART = 3511;
	IOLKHFCLGFP_BEYOND_POP_UP_REFRESH_TYPE_ALL = 3512;
	IOLKHFCLGFP_BEYOND_MONSTER_PATROL_SPEED_LEVEL_TYPE_IDLE = 3600;
	IOLKHFCLGFP_BEYOND_MONSTER_PATROL_SPEED_LEVEL_TYPE_WALK = 3601;
	IOLKHFCLGFP_BEYOND_MONSTER_PATROL_SPEED_LEVEL_TYPE_RUN = 3602;
	IOLKHFCLGFP_BEYOND_MONSTER_PATROL_SPEED_LEVEL_TYPE_SPRINT = 3603;
	IOLKHFCLGFP_BEYOND_MONSTER_PATROL_ROUTE_POINT_TYPE_NORMAL_MOVE = 3700;
	IOLKHFCLGFP_BEYOND_MONSTER_PATROL_ROUTE_POINT_TYPE_MOVE_AFTER_ROT = 3701;
	IOLKHFCLGFP_BEYOND_MONSTER_PATROL_MOVE_TYPE_ONCE = 3800;
	IOLKHFCLGFP_BEYOND_MONSTER_PATROL_MOVE_TYPE_ROUND = 3801;
	IOLKHFCLGFP_BEYOND_MONSTER_PATROL_MOVE_TYPE_LOOP = 3802;
	IOLKHFCLGFP_BEYOND_HIT_LEVEL_TYPE_MUTE = 3900;
	IOLKHFCLGFP_BEYOND_HIT_LEVEL_TYPE_SHAKE = 3901;
	IOLKHFCLGFP_BEYOND_HIT_LEVEL_TYPE_LIGHT = 3902;
	IOLKHFCLGFP_BEYOND_HIT_LEVEL_TYPE_HEAVY = 3903;
	IOLKHFCLGFP_BEYOND_HIT_LEVEL_TYPE_AIR = 3904;
	IOLKHFCLGFP_BEYOND_ATTACK_DAMAGE_ATTENUATION_DISTANCE_TYPE_BORN_POS = 4000;
	IOLKHFCLGFP_BEYOND_ATTACK_DAMAGE_ATTENUATION_DISTANCE_TYPE_CUR_POS = 4001;
	IOLKHFCLGFP_BEYOND_SETTLE_STATUS_NONE = 4100;
	IOLKHFCLGFP_BEYOND_SETTLE_STATUS_SUCC = 4101;
	IOLKHFCLGFP_BEYOND_SETTLE_STATUS_FAIL = 4102;
	IOLKHFCLGFP_BEYOND_SETTLE_STATUS_ESCAPE = 4103;
	IOLKHFCLGFP_BEYOND_STUFF_RARITY_WHITE = 4200;
	IOLKHFCLGFP_BEYOND_STUFF_RARITY_GREEN = 4201;
	IOLKHFCLGFP_BEYOND_STUFF_RARITY_BLUE = 4202;
	IOLKHFCLGFP_BEYOND_STUFF_RARITY_PURPLE = 4203;
	IOLKHFCLGFP_BEYOND_STUFF_RARITY_ORANGE = 4204;
	IOLKHFCLGFP_BEYOND_STUFF_CATEGORY_EQUIP = 4300;
	IOLKHFCLGFP_BEYOND_STUFF_CATEGORY_MATERIAL = 4301;
	IOLKHFCLGFP_BEYOND_STUFF_CATEGORY_CONSUMABLE = 4302;
	IOLKHFCLGFP_BEYOND_STUFF_CATEGORY_PRECIOUS = 4303;
	IOLKHFCLGFP_BEYOND_DROP_STUFF_OUTPUT_TYPE_SHARE = 4350;
	IOLKHFCLGFP_BEYOND_DROP_STUFF_OUTPUT_TYPE_INDEPENDENT = 4351;
	IOLKHFCLGFP_BEYOND_BASE_PROP_TYPE_HP = 4400;
	IOLKHFCLGFP_BEYOND_BASE_PROP_TYPE_HP_PERCENT = 4401;
	IOLKHFCLGFP_BEYOND_BASE_PROP_TYPE_ATTACK = 4402;
	IOLKHFCLGFP_BEYOND_BASE_PROP_TYPE_ATTACK_PERCENT = 4403;
	IOLKHFCLGFP_BEYOND_BASE_PROP_TYPE_DEFENSE = 4404;
	IOLKHFCLGFP_BEYOND_BASE_PROP_TYPE_DEFENSE_PERCENT = 4405;
	IOLKHFCLGFP_BEYOND_BASE_PROP_TYPE_FIRE_SUB_HURT = 4406;
	IOLKHFCLGFP_BEYOND_BASE_PROP_TYPE_ELEC_SUB_HURT = 4407;
	IOLKHFCLGFP_BEYOND_BASE_PROP_TYPE_WATER_SUB_HURT = 4408;
	IOLKHFCLGFP_BEYOND_BASE_PROP_TYPE_GRASS_SUB_HURT = 4409;
	IOLKHFCLGFP_BEYOND_BASE_PROP_TYPE_WIND_SUB_HURT = 4410;
	IOLKHFCLGFP_BEYOND_BASE_PROP_TYPE_ROCK_SUB_HURT = 4411;
	IOLKHFCLGFP_BEYOND_BASE_PROP_TYPE_ICE_SUB_HURT = 4412;
	IOLKHFCLGFP_BEYOND_BASE_PROP_TYPE_CRITICAL = 4413;
	IOLKHFCLGFP_BEYOND_BASE_PROP_TYPE_CRITICAL_HURT = 4414;
	IOLKHFCLGFP_BEYOND_BASE_PROP_TYPE_HEAL_ADD = 4415;
	IOLKHFCLGFP_BEYOND_BASE_PROP_TYPE_HEALED_ADD = 4416;
	IOLKHFCLGFP_BEYOND_BASE_PROP_TYPE_FIRE_ADD_HURT = 4417;
	IOLKHFCLGFP_BEYOND_BASE_PROP_TYPE_ELEC_ADD_HURT = 4418;
	IOLKHFCLGFP_BEYOND_BASE_PROP_TYPE_WATER_ADD_HURT = 4419;
	IOLKHFCLGFP_BEYOND_BASE_PROP_TYPE_GRASS_ADD_HURT = 4420;
	IOLKHFCLGFP_BEYOND_BASE_PROP_TYPE_WIND_ADD_HURT = 4421;
	IOLKHFCLGFP_BEYOND_BASE_PROP_TYPE_ROCK_ADD_HURT = 4422;
	IOLKHFCLGFP_BEYOND_BASE_PROP_TYPE_ICE_ADD_HURT = 4423;
	IOLKHFCLGFP_BEYOND_BASE_PROP_TYPE_PHYSICAL_ADD_HURT = 4424;
	IOLKHFCLGFP_BEYOND_ELEMENT_REACTION_TYPE_NONE = 4700;
	IOLKHFCLGFP_BEYOND_ELEMENT_REACTION_TYPE_EXPLODE = 4701;
	IOLKHFCLGFP_BEYOND_ELEMENT_REACTION_TYPE_STREAM = 4702;
	IOLKHFCLGFP_BEYOND_ELEMENT_REACTION_TYPE_BURNING = 4703;
	IOLKHFCLGFP_BEYOND_ELEMENT_REACTION_TYPE_BURNED = 4704;
	IOLKHFCLGFP_BEYOND_ELEMENT_REACTION_TYPE_WET = 4705;
	IOLKHFCLGFP_BEYOND_ELEMENT_REACTION_TYPE_OVERGROW = 4706;
	IOLKHFCLGFP_BEYOND_ELEMENT_REACTION_TYPE_MELT = 4707;
	IOLKHFCLGFP_BEYOND_ELEMENT_REACTION_TYPE_FREEZE = 4708;
	IOLKHFCLGFP_BEYOND_ELEMENT_REACTION_TYPE_ANTI_FIRE = 4709;
	IOLKHFCLGFP_BEYOND_ELEMENT_REACTION_TYPE_ROCK = 4710;
	IOLKHFCLGFP_BEYOND_ELEMENT_REACTION_TYPE_SLOW_DOWN = 4711;
	IOLKHFCLGFP_BEYOND_ELEMENT_REACTION_TYPE_SHOCK = 4712;
	IOLKHFCLGFP_BEYOND_ELEMENT_REACTION_TYPE_WIND = 4713;
	IOLKHFCLGFP_BEYOND_ELEMENT_REACTION_TYPE_ELECTRIC = 4714;
	IOLKHFCLGFP_BEYOND_ELEMENT_REACTION_TYPE_FIRE = 4715;
	IOLKHFCLGFP_BEYOND_ELEMENT_REACTION_TYPE_SUPERCONDUCTOR = 4716;
	IOLKHFCLGFP_BEYOND_ELEMENT_REACTION_TYPE_SWIRL_FIRE = 4717;
	IOLKHFCLGFP_BEYOND_ELEMENT_REACTION_TYPE_SWIRL_WATER = 4718;
	IOLKHFCLGFP_BEYOND_ELEMENT_REACTION_TYPE_SWIRL_ELECTRIC = 4719;
	IOLKHFCLGFP_BEYOND_ELEMENT_REACTION_TYPE_SWIRL_ICE = 4720;
	IOLKHFCLGFP_BEYOND_ELEMENT_REACTION_TYPE_SWIRL_FIRE_ACCUMULATE = 4721;
	IOLKHFCLGFP_BEYOND_ELEMENT_REACTION_TYPE_SWIRL_WATER_ACCUMULATE = 4722;
	IOLKHFCLGFP_BEYOND_ELEMENT_REACTION_TYPE_SWIRL_ELECTRIC_ACCUMULATE = 4723;
	IOLKHFCLGFP_BEYOND_ELEMENT_REACTION_TYPE_SWIRL_ICE_ACCUMULATE = 4724;
	IOLKHFCLGFP_BEYOND_ELEMENT_REACTION_TYPE_STICK_ROCK = 4725;
	IOLKHFCLGFP_BEYOND_ELEMENT_REACTION_TYPE_STICK_WATER = 4726;
	IOLKHFCLGFP_BEYOND_ELEMENT_REACTION_TYPE_CRYSTALLIZE_FIRE = 4727;
	IOLKHFCLGFP_BEYOND_ELEMENT_REACTION_TYPE_CRYSTALLIZE_WATER = 4728;
	IOLKHFCLGFP_BEYOND_ELEMENT_REACTION_TYPE_CRYSTALLIZE_ELECTRIC = 4729;
	IOLKHFCLGFP_BEYOND_ELEMENT_REACTION_TYPE_CRYSTALLIZE_ICE = 4730;
	IOLKHFCLGFP_BEYOND_ELEMENT_REACTION_TYPE_FROZEN_BROKEN = 4731;
	IOLKHFCLGFP_BEYOND_ELEMENT_REACTION_TYPE_STICK_GRASS = 4732;
	IOLKHFCLGFP_BEYOND_ELEMENT_REACTION_TYPE_OVERDOSE = 4733;
	IOLKHFCLGFP_BEYOND_ELEMENT_REACTION_TYPE_OVERDOSE_ELECTRIC = 4734;
	IOLKHFCLGFP_BEYOND_ELEMENT_REACTION_TYPE_OVERDOSE_GRASS = 4735;
	IOLKHFCLGFP_BEYOND_ELEMENT_REACTION_TYPE_OVERGROW_MUSHROOM_FIRE = 4736;
	IOLKHFCLGFP_BEYOND_ELEMENT_REACTION_TYPE_OVERGROW_MUSHROOM_ELECTRIC = 4737;
	IOLKHFCLGFP_BEYOND_ELEMENT_REACTION_TYPE_PHLOGISTON_SOLIDIFICATION = 4738;
	IOLKHFCLGFP_BEYOND_ELEMENT_REACTION_TYPE_PHLOGISTON_SOLIDIFICATION_END = 4739;
	IOLKHFCLGFP_BEYOND_ELEMENT_REACTION_TYPE_MOON_SHOCK = 4740;
	IOLKHFCLGFP_BEYOND_ELEMENT_REACTION_TYPE_MOON_OVERGROW = 4741;
	IOLKHFCLGFP_BEYOND_ELEMENT_REACTION_TYPE_MOON_CRYSTALLIZE_WATER = 4742;
	IOLKHFCLGFP_BEYOND_BAG_STUFF_CHANGE_ACTION_DESTROY = 4900;
	IOLKHFCLGFP_BEYOND_BAG_STUFF_CHANGE_ACTION_DROP = 4901;
	IOLKHFCLGFP_BEYOND_BAG_STUFF_CHANGE_ACTION_USE = 4902;
	IOLKHFCLGFP_BEYOND_BAG_STUFF_CHANGE_ACTION_DIE_DROP = 4903;
	IOLKHFCLGFP_BEYOND_BAG_STUFF_CHANGE_ACTION_SHOP_TRADE = 4904;
	IOLKHFCLGFP_BEYOND_BAG_STUFF_CHANGE_ACTION_BLUEPRINT_OPERATION = 4905;
	IOLKHFCLGFP_BEYOND_BAG_STUFF_CHANGE_ACTION_PICK_UP = 4950;
	IOLKHFCLGFP_BEYOND_SCAN_ENTITY_STATE_NONE = 5000;
	IOLKHFCLGFP_BEYOND_SCAN_ENTITY_STATE_AVAILABLE_TARGET = 5001;
	IOLKHFCLGFP_BEYOND_SCAN_ENTITY_STATE_AVAILABLE_NOT_TARGET = 5002;
	IOLKHFCLGFP_BEYOND_SCAN_ENTITY_STATE_NOT_AVAILABLE = 5003;
	IOLKHFCLGFP_BEYOND_SCAN_ENTITY_SCORE_RULE_TYPE_VIEW = 5100;
	IOLKHFCLGFP_BEYOND_SCAN_ENTITY_SCORE_RULE_TYPE_DISTANCE = 5101;
	IOLKHFCLGFP_BEYOND_ENDURE_STATE_TYPE_NORMAL = 5200;
	IOLKHFCLGFP_BEYOND_ENDURE_STATE_TYPE_RECOVER = 5201;
	IOLKHFCLGFP_BEYOND_ENDURE_STATE_TYPE_PROTECT = 5202;
	IOLKHFCLGFP_BEYOND_CHAT_CHANNEL_TYPE_ARMY = 5300;
	IOLKHFCLGFP_BEYOND_CHAT_CHANNEL_TYPE_CUSTOM_PLAYER = 5301;
	IOLKHFCLGFP_BEYOND_ABILITY_SHOW_DAMAGE_TEXT_TYPE_NONE = 5400;
	IOLKHFCLGFP_BEYOND_ABILITY_SHOW_DAMAGE_TEXT_TYPE_NORMAL = 5401;
	IOLKHFCLGFP_BEYOND_ABILITY_SHOW_DAMAGE_TEXT_TYPE_CRITICAL = 5402;
	IOLKHFCLGFP_BEYOND_FIXED_POS_ROT_MOVER_MOVE_TYPE_IMMEDIATE = 5500;
	IOLKHFCLGFP_BEYOND_FIXED_POS_ROT_MOVER_MOVE_TYPE_UNIFORM_LINEAR = 5501;
	IOLKHFCLGFP_BEYOND_FIXED_POS_ROT_MOVER_PARAM_TRANS_TYPE_SPEED_BASE = 5600;
	IOLKHFCLGFP_BEYOND_FIXED_POS_ROT_MOVER_PARAM_TRANS_TYPE_TIME_BASE = 5601;
	IOLKHFCLGFP_BEYOND_PLAY_TYPE_TRIAL = 5700;
	IOLKHFCLGFP_BEYOND_PLAY_TYPE_ROOM = 5701;
	IOLKHFCLGFP_BEYOND_PLAY_TYPE_MATCH = 5702;
	IOLKHFCLGFP_BEYOND_PLAYER_INPUT_DEVICE_TYPE_KEYBOARD = 5800;
	IOLKHFCLGFP_BEYOND_PLAYER_INPUT_DEVICE_TYPE_CONTROLLER = 5801;
	IOLKHFCLGFP_BEYOND_PLAYER_INPUT_DEVICE_TYPE_TOUCH_SCREEN = 5802;
	IOLKHFCLGFP_BEYOND_MONSTER_VERSION_TYPE_MONSTER_V1 = 5900;
	IOLKHFCLGFP_BEYOND_MONSTER_VERSION_TYPE_MONSTER_V2 = 5901;
	IOLKHFCLGFP_BEYOND_CLIENT_AI_TARGET_TYPE_THREAT = 6000;
	IOLKHFCLGFP_BEYOND_CLIENT_AI_TARGET_TYPE_OWNER = 6001;
	IOLKHFCLGFP_BEYOND_CLIENT_AI_TARGET_TYPE_CHILDREN = 6002;
	IOLKHFCLGFP_BEYOND_CLIENT_AI_TARGET_TYPE_SELF = 6003;
	IOLKHFCLGFP_BEYOND_CLIENT_AI_TARGET_TYPE_TARGET = 6004;
	IOLKHFCLGFP_BEYOND_CLIENT_AI_TARGET_TYPE_TARGET_TEAM = 6005;
	IOLKHFCLGFP_BEYOND_CLIENT_AI_TARGET_TYPE_COMMAND = 6006;
	IOLKHFCLGFP_BEYOND_CLIENT_AI_TARGET_TYPE_LEVEL_ENTITY = 6007;
	IOLKHFCLGFP_BEYOND_CLIENT_AI_TACTIC_ROTATE_DIR_TYPE_DEFAULT = 6100;
	IOLKHFCLGFP_BEYOND_CLIENT_AI_TACTIC_ROTATE_DIR_TYPE_CLOCKWISE = 6101;
	IOLKHFCLGFP_BEYOND_CLIENT_AI_TACTIC_ROTATE_DIR_TYPE_ANTICLOCKWISE = 6102;
	IOLKHFCLGFP_BEYOND_CLIENT_AI_TACTIC_TYPE_IDLE = 6200;
	IOLKHFCLGFP_BEYOND_CLIENT_AI_TACTIC_TYPE_MOVE_TO_MANUAL_POSITION = 6201;
	IOLKHFCLGFP_BEYOND_CLIENT_AI_TACTIC_TYPE_MOVE_TO_MANUAL_TARGET = 6202;
	IOLKHFCLGFP_BEYOND_CLIENT_AI_TACTIC_TYPE_ROTATE_TO_MANUAL_ROTATION = 6203;
	IOLKHFCLGFP_BEYOND_CLIENT_AI_TACTIC_TYPE_ROTATE_MANUAL_ANGLE = 6204;
	IOLKHFCLGFP_BEYOND_CLIENT_AI_TACTIC_TYPE_MELEE_CHARGE = 6205;
	IOLKHFCLGFP_BEYOND_CLIENT_AI_TACTIC_TYPE_FLEE = 6206;
	IOLKHFCLGFP_BEYOND_CLIENT_AI_TACTIC_TYPE_WANDER = 6207;
	IOLKHFCLGFP_BEYOND_CLIENT_AI_TACTIC_TYPE_RETURN_TO_BORN = 6208;
	IOLKHFCLGFP_BEYOND_CLIENT_AI_TACTIC_TYPE_FACING_MOVE = 6209;
	IOLKHFCLGFP_BEYOND_CLIENT_AI_TACTIC_TYPE_FOLLOW_SERVER_ROUTE = 6210;
	IOLKHFCLGFP_BEYOND_CLIENT_AI_TACTIC_TYPE_ROTATE_TO_MANUAL_TARGET = 6211;
	IOLKHFCLGFP_BEYOND_BOOL_TYPE_FALSE = 6300;
	IOLKHFCLGFP_BEYOND_BOOL_TYPE_TRUE = 6301;
	IOLKHFCLGFP_BEYOND_CLIENT_TARGET_SORT_TYPE_DEFAULT = 1000001;
	IOLKHFCLGFP_BEYOND_CLIENT_TARGET_SORT_TYPE_RANDOM = 1000002;
	IOLKHFCLGFP_BEYOND_CLIENT_TARGET_SORT_TYPE_NEAREST = 1000003;
	IOLKHFCLGFP_BEYOND_CLIENT_FILTER_TYPE_BOOL = 1000010;
	IOLKHFCLGFP_BEYOND_CLIENT_FILTER_TYPE_INT = 10000011;
}
