syntax = "proto3";

import "AvatarBase.proto";
import "FEFGACGJEBK.proto";
import "GadgetBase.proto";
import "IOLKHFCLGFP.proto";
import "LGEOBLBDPIN.proto";
import "MonsterBase.proto";
import "PlayerBase.proto";

message KJLCAPIOBMP {
	uint32 MDJKJOJGGCP = 1;
	IOLKHFCLGFP LLEFEOGNFFP = 2;
	repeated LGEOBLBDPIN JOLOHNCKMIJ = 3;
	bool JBGCPHECNGN = 5;
	bool JKCNBGPDBCO = 6;
	uint32 IJPMIIEHNCI = 7;
	uint32 DEABEMPJLNJ = 8;
	bool CCGLDFNOELK = 9;
	FEFGACGJEBK CJHKDGIADJP = 10;
	repeated int32 tag_list = 51;
	uint32 JALJKOGHPHI = 52;
	oneof JIOINBGNFBD {
		_GadgetBase gadget_base = 11;
		_PlayerBase player_base = 12;
		_AvatarBase avatar_base = 13;
		_MonsterBase monster_base = 14;
	}
}
