syntax = "proto3";

import "CDJPDNDBAGH.proto";
import "CGAJAKIJNFL.proto";
import "ELKPHNLMOJB.proto";
import "EMMLFLKEIAN.proto";
import "KGENIDEPJMK.proto";
import "KONOKPCPDPC.proto";
import "MEFNGHLJCAI.proto";
import "NGBPIJGDGPI.proto";
import "NIMHJIDLBKP.proto";
import "OLFFNALHHCO.proto";
import "PLKFPJGCBBB.proto";

message LAFFFGPGHDH {
	repeated PLKFPJGCBBB GEBHOILEAGO = 3;
	KONOKPCPDPC LNOINOHAFFI = 5;
	KGENIDEPJMK KBCKKEAPNGB = 8;
	ELKPHNLMOJB NLMJMCKPJJG = 2;
	CDJPDNDBAGH MNNFGCFFBOB = 12;
	EMMLFLKEIAN MJDOJABIPEL = 13;
	repeated uint32 HNLHFBBGHIP = 837;
	CGAJAKIJNFL EPDMDCMHJMJ = 14;
	OLFFNALHHCO EKAONJCFAGO = 11;
	repeated MEFNGHLJCAI OMILKHLIMOM = 1780;
	NGBPIJGDGPI AHECMLKEFLG = 7;
	NIMHJIDLBKP goal = 9;
	uint32 NAOIOBDGKHD = 15;
	uint32 KKMFNPMMLFO = 10;
	uint32 OBPKOCGGNPL = 1;
	uint32 GCGNLEFLDGI = 6;
	uint32 DMCFGNNPDOI = 1469;
	bool HNNGHPMELPI = 4;
	uint32 ACJHLNHGCAM = 1890;
}
