syntax = "proto3";

import "BDPBPFLPMEP.proto";
import "BeyondParamValueArmy.proto";
import "BeyondParamValueBool.proto";
import "BeyondParamValueBoolList.proto";
import "BeyondParamValueCompType.proto";
import "BeyondParamValueEntity.proto";
import "BeyondParamValueEntityList.proto";
import "BeyondParamValueEnum.proto";
import "BeyondParamValueFloat.proto";
import "BeyondParamValueFloatList.proto";
import "BeyondParamValueGuid.proto";
import "BeyondParamValueGuidList.proto";
import "BeyondParamValueInt.proto";
import "BeyondParamValueIntList.proto";
import "BeyondParamValueString.proto";
import "BeyondParamValueStringList.proto";
import "BeyondParamValueVariable.proto";
import "BeyondParamValueVector3.proto";
import "BeyondParamValueVector3List.proto";
import "BLCAJEIGNMK.proto";
import "CMKADHFAEJC.proto";
import "EICBDBGHEEL.proto";
import "ENPPLONOPPA.proto";
import "GMCFIBAOAHI.proto";
import "JFMHJDKBOEL.proto";
import "LPLEBJLAIJC.proto";
import "LPPCAKFKLJL.proto";
import "MBKBKMDFGLM.proto";
import "MGJDEEIHCAJ.proto";
import "MHJPFGAKHDM.proto";
import "PDPLJKABMKC.proto";

message MCPKFEHLIEN {
	CMKADHFAEJC NKJKMEKPPJD = 1;
	LPPCAKFKLJL GIKCIMBCPOJ = 2;
	oneof detail {
		_BeyondParamValueEntity beyond_param_value_entity = 11;
		_BeyondParamValueGuid beyond_param_value_guid = 12;
		_BeyondParamValueInt beyond_param_value_int = 13;
		_BeyondParamValueBool beyond_param_value_bool = 14;
		_BeyondParamValueFloat beyond_param_value_float = 15;
		_BeyondParamValueString beyond_param_value_string = 16;
		_BeyondParamValueGuidList beyond_param_value_guid_list = 17;
		_BeyondParamValueIntList beyond_param_value_int_list = 18;
		_BeyondParamValueBoolList beyond_param_value_bool_list = 19;
		_BeyondParamValueFloatList beyond_param_value_float_list = 20;
		_BeyondParamValueStringList beyond_param_value_string_list = 21;
		_BeyondParamValueVector3 beyond_param_value_vector_3 = 22;
		_BeyondParamValueEntityList beyond_param_value_entity_list = 23;
		_BeyondParamValueEnum beyond_param_value_enum = 24;
		_BeyondParamValueVector3List beyond_param_value_vector_3_list = 25;
		_BeyondParamValueVariable beyond_param_value_variable = 26;
		_BeyondParamValueArmy beyond_param_value_army = 27;
		_BeyondParamValueCompType beyond_param_value_comp_type = 28;
		MHJPFGAKHDM beyond_param_value_category_type = 29;
		BLCAJEIGNMK beyond_param_value_config_reference = 30;
		MGJDEEIHCAJ beyond_param_value_entity_reference = 31;
		ENPPLONOPPA beyond_param_value_config_reference_list = 32;
		PDPLJKABMKC beyond_param_value_entity_reference_list = 33;
		LPLEBJLAIJC beyond_param_value_army_list = 34;
		MBKBKMDFGLM beyond_param_value_struct_const = 35;
		GMCFIBAOAHI beyond_param_value_struct_list_const = 36;
		BDPBPFLPMEP beyond_param_value_dict_const = 37;
		EICBDBGHEEL beyond_param_value_custom_value_snapshot = 38;
		JFMHJDKBOEL beyond_param_value_enum_list = 39;
	}
}
