syntax = "proto3";

enum MOBDIGEJPPN {
	MOBDIGEJPPN_BEYOND_COMP_TYPE_NONE = 0;
	MOBDIGEJPPN_BEYOND_COMP_TYPE_CUSTOM_VALUE = 1;
	MOBDIGEJPPN_BEYOND_COMP_TYPE_TIMER = 3;
	MOBDIGEJPPN_BEYOND_COMP_TYPE_MOVER = 4;
	MOBDIGEJPPN_BEYOND_COMP_TYPE_CLIENT_TRIGGER = 5;
	MOBDIGEJPPN_BEYOND_COMP_TYPE_EFFECT = 6;
	MOBDIGEJPPN_BEYOND_COMP_TYPE_BORN_POINT = 7;
	MOBDIGEJPPN_BEYOND_COMP_TYPE_COLLISION = 8;
	MOBDIGEJPPN_BEYOND_COMP_TYPE_FOLLOW_MOVE = 9;
	MOBDIGEJPPN_BEYOND_COMP_TYPE_BULLET_MOVE = 11;
	MOBDIGEJPPN_BEYOND_COMP_TYPE_HIT_DETECTION = 12;
	MOBDIGEJPPN_BEYOND_COMP_TYPE_CAMERA = 13;
	MOBDIGEJPPN_BEYOND_COMP_TYPE_ROLE_STATUS = 14;
	MOBDIGEJPPN_BEYOND_COMP_TYPE_AVATAR_DISTURBER = 15;
	MOBDIGEJPPN_BEYOND_COMP_TYPE_COUNT_DOWN = 16;
	MOBDIGEJPPN_BEYOND_COMP_TYPE_OPTION = 17;
	MOBDIGEJPPN_BEYOND_COMP_TYPE_COMBAT = 18;
	MOBDIGEJPPN_BEYOND_COMP_TYPE_HITBOX = 19;
	MOBDIGEJPPN_BEYOND_COMP_TYPE_BULLET_PATTERN = 20;
	MOBDIGEJPPN_BEYOND_COMP_TYPE_TEMP_ATTACH_POINT = 21;
	MOBDIGEJPPN_BEYOND_COMP_TYPE_CUSTOM_SKILL = 22;
	MOBDIGEJPPN_BEYOND_COMP_TYPE_INTEE = 23;
	MOBDIGEJPPN_BEYOND_COMP_TYPE_MP_ACTION = 24;
	MOBDIGEJPPN_BEYOND_COMP_TYPE_TAG = 25;
	MOBDIGEJPPN_BEYOND_COMP_TYPE_ENMITY = 26;
	MOBDIGEJPPN_BEYOND_COMP_TYPE_NAMEPLATE = 27;
	MOBDIGEJPPN_BEYOND_COMP_TYPE_TALK = 28;
	MOBDIGEJPPN_BEYOND_COMP_TYPE_SOUND_EFFECT = 29;
	MOBDIGEJPPN_BEYOND_COMP_TYPE_MONSTER_PATROL = 30;
	MOBDIGEJPPN_BEYOND_COMP_TYPE_LEVEL_STATE_MACHINE = 31;
	MOBDIGEJPPN_BEYOND_COMP_TYPE_MINIMAP_MARK = 32;
	MOBDIGEJPPN_BEYOND_COMP_TYPE_STUFF_BAG = 33;
	MOBDIGEJPPN_BEYOND_COMP_TYPE_EQUIP_STUFF_BAG = 34;
	MOBDIGEJPPN_BEYOND_COMP_TYPE_SHOP = 35;
	MOBDIGEJPPN_BEYOND_COMP_TYPE_DROP_GATHER = 36;
	MOBDIGEJPPN_BEYOND_COMP_TYPE_DROP_STUFF = 37;
	MOBDIGEJPPN_BEYOND_COMP_TYPE_LIGHT_GROUP = 38;
	MOBDIGEJPPN_BEYOND_COMP_TYPE_SCAN_ENTITY = 39;
	MOBDIGEJPPN_BEYOND_COMP_TYPE_POP_UP = 40;
	MOBDIGEJPPN_BEYOND_COMP_TYPE_OBSTACLE = 41;
	MOBDIGEJPPN_BEYOND_COMP_TYPE_MONSTER_AI_COMP = 42;
	MOBDIGEJPPN_BEYOND_COMP_TYPE_WATERFALL_COMP = 43;
	MOBDIGEJPPN_BEYOND_COMP_TYPE_WATER_CUBE_COMP = 44;
	MOBDIGEJPPN_BEYOND_COMP_TYPE_ARRAYSIZE = 45;
}
