syntax = "proto3";

enum PlatformType {
	EDITOR = 0;
	IOS = 1;
	ANDROID = 2;
	PC = 3;
	PS4 = 4;
	SERVER = 5;
	CLOUD_ANDROID = 6;
	CLOUD_IOS = 7;
	PS5 = 8;
	CLOUD_WEB = 9;
	CLOUD_TV = 10;
	CLOUD_MAC = 11;
	CLOUD_PC = 12;
	CLOUD_THIRD_PARTY_MOBILE = 13;
	CLOUD_THIRD_PARTY_PC = 14;
	PLATFORM_TYPE_CLOUD_WEB_ANDROID = 15;
	PLATFORM_TYPE_CLOUD_WEB_IOS = 16;
	PLATFORM_TYPE_CLOUD_WEB_PC = 17;
	PLATFORM_TYPE_CLOUD_WEB_MAC = 18;
	PLATFORM_TYPE_CLOUD_WEB_TOUCH = 19;
	PLATFORM_TYPE_CLOUD_WEB_KEYBOARD = 20;
	PLATFORM_TYPE_XBOX_SCARLETT = 21;
	PLATFORM_TYPE_OPEN_HARMONY = 22;
}
