syntax = "proto3";

import "AIOGAJBLMAB.proto";
import "FeatureBlockInfo.proto";
import "JKHIHMAFKKI.proto";
import "ResVersionConfig.proto";
import "ShortAbilityHashPair.proto";
import "StopServerInfo.proto";

message PlayerLoginRsp {
	
	map<uint32, BlockInfo> block_info_map = 1926;
	
	map<uint64, LAALLMKMLBC> HNBLPILNCND = 173;
	map<string, int32> ability_hash_map = 5;
	ResVersionConfig next_res_version_config = 1952;
	
	
	
	
	AIOGAJBLMAB FJIJEKMNHMB = 1905;
	
	ResVersionConfig res_version_config = 73;
	repeated FeatureBlockInfo feature_block_info_list = 34;
	repeated ShortAbilityHashPair short_ability_hash_map = 273;
	
	JKHIHMAFKKI FMDPGOIOHNB = 605;
	StopServerInfo JHNMMAKFMJG = 1494;
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
}