syntax = "proto3";

import "EnterType.proto";
import "IEHCJBPPCMD.proto";
import "LimitedRegionInfo.proto";
import "MapLayerInfo.proto";
import "MirrorWorldSceneDetail.proto";
import "NJFHIBIMPPP.proto";
import "Vector.proto";

message PlayerEnterSceneNotify {
	IEHCJBPPCMD HJGLNPEOIDE = 785;
	_MapLayerInfo _map_layer_info = 724;
	string scene_transaction = 205;
	_MirrorWorldSceneDetail _mirror_world_scene_detail = 150;
	Vector pos = 13;
	Vector BNNBCCNPOJG = 9;
	NJFHIBIMPPP JEGBHLHCKLD = 1289;
	repeated uint32 scene_tag_id_list = 6;
	_LimitedRegionInfo _limited_region_info = 589;
	Vector EOKPAOCNGBM = 751;
	uint32 enter_reason = 1911 [(ys_custom).is_masked = true, (ys_custom).value_mask = "(val ^ 43962) + 40350"];
	uint32 enter_scene_token = 2 [(ys_custom).is_masked = true, (ys_custom).value_mask = "(val ^ 57361) - 22665"];
	uint32 FCKJJGAHHLI = 1416 [(ys_custom).is_masked = true, (ys_custom).value_mask = "(val - 7304) ^ 7061", (ys_custom).value_unmask = "(val ^ 7061) + 7304"];
	uint32 create_player_uid = 983 [(ys_custom).is_masked = true, (ys_custom).value_mask = "(val - 50775) ^ 38388"];
	bool is_skip_ui = 1551;
	bool is_first_login_enter_scene = 8;
	uint32 target_uid = 15 [(ys_custom).is_masked = true, (ys_custom).value_mask = "(val - 30259) ^ 4145"];
	uint32 dungeon_id = 12 [(ys_custom).is_masked = true, (ys_custom).value_mask = "(val ^ 27544) - 17829"];
	uint32 _dungeon_difficulty_type = 1292 [(ys_custom).is_masked = true, (ys_custom).value_mask = "(val ^ 60001) + 6461"];
	EnterType type = 4;
	uint32 scene_id = 11 [(ys_custom).is_masked = true, (ys_custom).value_mask = "(val - 49379) ^ 11523"];
	uint32 _template_loading_id = 344 [(ys_custom).is_masked = true, (ys_custom).value_mask = "(val - 3554) ^ 2221"];
	uint32 prev_scene_id = 5 [(ys_custom).is_masked = true, (ys_custom).value_mask = "(val ^ 39512) - 40922"];
	uint64 scene_begin_time = 10 [(ys_custom).is_masked = true, (ys_custom).value_mask = "(val ^ 27843) + 16749"];
	uint32 world_level = 3 [(ys_custom).is_masked = true, (ys_custom).value_mask = "(val ^ 31579) + 19873"];
	uint32 world_type = 1146 [(ys_custom).is_masked = true, (ys_custom).value_mask = "(val + 30022) ^ 64981"];
}
