syntax = "proto3";

import "BKHAILJHCAO.proto";
import "CHGPCNHCILF.proto";
import "MathQuaternion.proto";
import "Vector.proto";

message RoutePoint {
	enum FJPKNGDFMHN {
		FJPKNGDFMHN_KEEP_MOVE = 0;
		FJPKNGDFMHN_TELEPORT_BY_OBSTACLE = 1;
		FJPKNGDFMHN_FADE_IN_OUT_TELEPORT_BY_OBSTACLE = 2;
	}

	Vector position = 1;
	
	
	
	BKHAILJHCAO point_type = 24;
	CHGPCNHCILF action = 25;
	
	
	
	
	FJPKNGDFMHN NEIJHFPBJBE = 30;
	oneof move_params {
		
		
	}
	oneof rotate_params {
		Vector rotation = 21;
		MathQuaternion rotation_speed = 22;
		MathQuaternion axis_speed = 23;
	}
}