syntax = "proto3";

import "AvatarExcelInfo.proto";
import "CurVehicleInfo.proto";
import "SceneReliquaryInfo.proto";
import "SceneWeaponInfo.proto";
import "ServerBuff.proto";

message SceneAvatarInfo {
	
	
	
	
	repeated 
	
	repeated 
	SceneWeaponInfo weapon = 8;
	repeated SceneReliquaryInfo reliquary_list = 9;
	
	repeated 
	map<uint32, uint32> skill_level_map = 13;
	map<uint32, uint32> proud_skill_extra_level_map = 14;
	repeated ServerBuff server_buff_list = 15;
	repeated 
	
	
	
	CurVehicleInfo cur_vehicle_info = 20;
	AvatarExcelInfo excel_info = 21;
	
	
	
	
	
	repeated 
	repeated 
	repeated 
	repeated 
}