syntax = "proto3";

import "AbilityControlBlock.proto";
import "AbilitySyncStateInfo.proto";
import "AvatarInfo.proto";
import "SceneAvatarInfo.proto";
import "SceneEntityInfo.proto";
import "ServerBuff.proto";

message SceneTeamAvatar {
	AbilitySyncStateInfo LBIJJANPOOL = 11;
	SceneEntityInfo scene_entity_info = 6;
	SceneAvatarInfo scene_avatar_info = 8;
	AvatarInfo avatar_info = 3;
	AbilitySyncStateInfo DMLKOPFAJAI = 5;
	repeated ServerBuff server_buff_list = 7;
	AbilityControlBlock ability_control_block = 10;
	
	
	
	
	
	
	
	
	
}