syntax = "proto3";

import "AnimatorParameterValueInfoPair.proto";
import "EntityAuthorityInfo.proto";
import "EntityClientData.proto";
import "EntityEnvironmentInfo.proto";
import "FightPropPair.proto";
import "ICFJCKPMDGJ.proto";
import "KJLCAPIOBMP.proto";
import "MIKFNKNAFFB.proto";
import "MotionInfo.proto";
import "PropPair.proto";
import "ProtEntityType.proto";
import "SceneAvatarInfo.proto";
import "SceneGadgetInfo.proto";
import "SceneMonsterInfo.proto";
import "SceneNpcInfo.proto";
import "ServerBuff.proto";

message SceneEntityInfo {
	ProtEntityType entity_type = 1;
	
	
	MotionInfo motion_info = 4;
	repeated PropPair prop_list = 5;
	repeated FightPropPair fight_prop_list = 6;
	
	repeated AnimatorParameterValueInfoPair animator_para_list = 9;
	
	
	EntityClientData entity_client_data = 19;
	repeated EntityEnvironmentInfo entity_environment_info_list = 20;
	EntityAuthorityInfo entity_authority_info = 21;
	repeated 
	repeated ServerBuff server_buff_list = 23;
	KJLCAPIOBMP NAPLGLENOKL = 24;
	ICFJCKPMDGJ AALLMDMBCCN = 25;
	
	MIKFNKNAFFB MMDFHOBIOFP = 27;
	oneof entity {
		SceneAvatarInfo avatar = 10;
		SceneMonsterInfo monster = 11;
		SceneNpcInfo npc = 12;
		SceneGadgetInfo gadget = 13;
	}
}