syntax = "proto3";

import "CustomGalleryInfo.proto";
import "GalleryStageType.proto";
import "PJAKMJEMAAC.proto";
import "SceneGalleryAkaFesArchaeologyInfo.proto";
import "SceneGalleryAkaFesRhythmInfo.proto";
import "SceneGalleryAnimalViewInfo.proto";
import "SceneGalleryAutoTimeStopInfo.proto";
import "SceneGalleryBalloonInfo.proto";
import "SceneGalleryBounceConjuringInfo.proto";
import "SceneGalleryBoxMatchInfo.proto";
import "SceneGalleryBrokenFloorInfo.proto";
import "SceneGalleryBulletInfo.proto";
import "SceneGalleryBuoyantCombatInfo.proto";
import "SceneGalleryCharAmusementInfo.proto";
import "SceneGalleryCoinCollectInfo.proto";
import "SceneGalleryCrystalLinkInfo.proto";
import "SceneGalleryDuelHeartInfo.proto";
import "SceneGalleryEffigyChallengeV2Info.proto";
import "SceneGalleryFallInfo.proto";
import "SceneGalleryFilmfestBattleInfo.proto";
import "SceneGalleryFilmfestSniperInfo.proto";
import "SceneGalleryFlightGearInfo.proto";
import "SceneGalleryFlowerInfo.proto";
import "SceneGalleryFungusFighterCaptureInfo.proto";
import "SceneGalleryFungusFighterTrainingInfo.proto";
import "SceneGalleryFungusFighterV2Info.proto";
import "SceneGalleryFungusFighterV3Info.proto";
import "SceneGalleryHandballInfo.proto";
import "SceneGalleryHideAndSeekInfo.proto";
import "SceneGalleryHideAndSeekV4Info.proto";
import "SceneGalleryHomeBalloonInfo.proto";
import "SceneGalleryHomeSeekFurnitureInfo.proto";
import "SceneGalleryInspirationSpurtInfo.proto";
import "SceneGalleryInstaleSprayInfo.proto";
import "SceneGalleryIrodoriMasterInfo.proto";
import "SceneGalleryIslandPartyDownHillInfo.proto";
import "SceneGalleryIslandPartyRaftInfo.proto";
import "SceneGalleryIslandPartySailInfo.proto";
import "SceneGalleryJourneyDiceInfo.proto";
import "SceneGalleryLanV3BoatMultiInfo.proto";
import "SceneGalleryLuminanceStoneChallengeInfo.proto";
import "SceneGalleryMuqadasPotionInfo.proto";
import "SceneGalleryPacmanInfo.proto";
import "SceneGalleryPhotoInfo.proto";
import "SceneGalleryProgressInfo.proto";
import "SceneGalleryQuickTimeCombatInfo.proto";
import "SceneGalleryRemusArenaInfo.proto";
import "SceneGallerySalvageEscortInfo.proto";
import "SceneGallerySalvagePreventInfo.proto";
import "SceneGallerySandwormInfo.proto";
import "SceneGallerySlimeCannonInfo.proto";
import "SceneGallerySorushTrialHitmanInfo.proto";
import "SceneGallerySorushTrialPhotoMatchInfo.proto";
import "SceneGallerySummerTimeV2BoatInfo.proto";
import "SceneGallerySumoInfo.proto";
import "SceneGalleryTargetShootingInfo.proto";
import "SceneGalleryTeamChainInfo.proto";
import "SceneGalleryTimeStopPhotoInfo.proto";
import "SceneGalleryTowerDefenseInfo.proto";
import "SceneGalleryTreasureHuntV4Info.proto";
import "SceneGalleryTreasureSeelieInfo.proto";
import "SceneGalleryVintageHuntingInfo.proto";
import "SceneGalleryWindFieldInfo.proto";

message SceneGalleryInfo {
	_CustomGalleryInfo _custom_gallery_info = 2;
	repeated SceneGalleryProgressInfo progress_info_list = 12;
	PJAKMJEMAAC JKCHCIJEECH = 444;
	uint32 gallery_id = 11;
	uint32 player_count = 9;
	uint32 end_time = 3;
	uint32 pre_start_end_time = 13;
	uint32 start_time = 6;
	GalleryStageType stage = 7;
	uint32 owner_uid = 8;
	uint64 JCGJHFHFELI = 873;
	oneof info {
		_SceneGalleryAkaFesArchaeologyInfo aka_fes_archaeology_info = 602;
		_SceneGalleryFlightGearInfo flight_gear_info = 794;
		SceneGalleryIslandPartyRaftInfo island_party_raft_info = 378;
		_SceneGalleryTowerDefenseInfo tower_defense_info = 1052;
		SceneGalleryBuoyantCombatInfo buoyant_combat_info = 645;
		SceneGalleryLuminanceStoneChallengeInfo luminance_stone_challenge_info = 763;
		_SceneGalleryQuickTimeCombatInfo quick_time_combat_info = 1576;
		SceneGalleryBulletInfo bullet_info = 10;
		_SceneGalleryInspirationSpurtInfo inspiration_spurt_info = 430;
		_SceneGalleryTimeStopPhotoInfo time_stop_photo_info = 930;
		SceneGalleryBounceConjuringInfo bounce_conjuring_info = 1210;
		SceneGalleryVintageHuntingInfo vintage_hunting_info = 105;
		SceneGalleryWindFieldInfo wind_field_info = 1077;
		_SceneGalleryFilmfestBattleInfo filmfest_battle_info = 1318;
		SceneGalleryFungusFighterTrainingInfo fungus_fighter_training_info = 984;
		_SceneGallerySorushTrialPhotoMatchInfo sorush_trial_photo_match_info = 1259;
		SceneGalleryHomeBalloonInfo home_balloon_info = 22;
		SceneGalleryBalloonInfo balloon_info = 5;
		SceneGallerySumoInfo sumo_info = 2013;
		SceneGalleryDuelHeartInfo duel_heart_info = 160;
		_SceneGalleryTargetShootingInfo target_shooting_info = 827;
		SceneGalleryHandballInfo handball_info = 209;
		SceneGalleryTeamChainInfo team_chain_info = 1138;
		_SceneGalleryFilmfestSniperInfo filmfest_sniper_info = 461;
		SceneGallerySummerTimeV2BoatInfo summer_time_v2_boat_info = 989;
		_SceneGallerySlimeCannonInfo slime_cannon_info = 1903;
		SceneGalleryHideAndSeekInfo hide_and_seek_info = 4;
		SceneGallerySalvageEscortInfo salvage_escort_info = 735;
		SceneGalleryTreasureSeelieInfo treasure_seelie_info = 311;
		SceneGallerySalvagePreventInfo salvage_prevent_info = 728;
		SceneGalleryHomeSeekFurnitureInfo home_seek_furniture_info = 552;
		SceneGalleryEffigyChallengeV2Info effigy_challenge_info = 350;
		_SceneGalleryFungusFighterV3Info fungus_fighter_v3_info = 1195;
		SceneGalleryIrodoriMasterInfo irodori_master_info = 939;
		SceneGalleryCharAmusementInfo char_amusement_info = 1804;
		_SceneGalleryPacmanInfo pacman_info = 1441;
		_SceneGalleryAnimalViewInfo animal_view_info = 1038;
		SceneGalleryIslandPartyDownHillInfo island_party_down_hill_info = 1652;
		SceneGalleryFungusFighterCaptureInfo fungus_fighter_capture_info = 995;
		SceneGalleryLanV3BoatMultiInfo boat_multi_info = 1841;
		_SceneGalleryAkaFesRhythmInfo aka_fes_rhythm_info = 1118;
		SceneGalleryCoinCollectInfo coin_collect_info = 1341;
		_SceneGalleryAutoTimeStopInfo auto_time_stop_info = 660;
		_SceneGalleryFungusFighterV2Info fungus_fighter_v2_info = 85;
		_SceneGalleryTreasureHuntV4Info treasure_hunt_v4_info = 1003;
		_SceneGalleryBoxMatchInfo box_match_info = 925;
		SceneGalleryInstaleSprayInfo instable_spray_info = 556;
		SceneGalleryFallInfo fall_info = 15;
		_SceneGalleryRemusArenaInfo remus_arena_info = 1380;
		SceneGalleryCrystalLinkInfo crystal_link_info = 324;
		SceneGalleryMuqadasPotionInfo muqadas_potion_info = 970;
		SceneGalleryBrokenFloorInfo broken_floor_info = 14;
		_SceneGalleryHideAndSeekV4Info hide_and_seek_v4_info = 1495;
		_SceneGallerySandwormInfo sandworm_info = 366;
		_SceneGalleryJourneyDiceInfo journey_dice_info = 1391;
		SceneGalleryFlowerInfo flower_info = 1;
		SceneGalleryIslandPartySailInfo island_party_sail_info = 1802;
		_SceneGalleryPhotoInfo photo_info = 779;
		_SceneGallerySorushTrialHitmanInfo sorush_trial_hitman_info = 158;
	}
}
