syntax = "proto3";

import "Birthday.proto";
import "FeatureBlockType.proto";
import "FriendEnterHomeOption.proto";
import "FriendOnlineState.proto";
import "PlatformType.proto";
import "ProfilePicture.proto";
import "SocialShowAvatarInfo.proto";

message SocialDetail {
	enum _DetailVersionType {
		_DETAIL_VERSION_TYPE_VERSION_NONE = 0;
		_DETAIL_VERSION_TYPE_V5_0 = 1;
		_DETAIL_VERSION_TYPE_V5_7 = 2;
	}

	
	
	
	
	
	Birthday birthday = 6;
	
	repeated 
	FriendOnlineState online_state = 9;
	
	
	
	
	
	
	
	
	
	
	
	
	repeated SocialShowAvatarInfo show_avatar_info_list = 22;
	repeated 
	FriendEnterHomeOption friend_enter_home_option = 24;
	ProfilePicture profile_picture = 25;
	
	
	
	
	
	PlatformType platform_type = 31;
	
	
	
	
	_DetailVersionType data_version = 36;
	
	
	
	
	
	
	repeated FeatureBlockType NGLAGEBDGBJ = 43;
}