syntax = "proto3";

import "VintageMarketDealInfo.proto";
import "VintageMarketStoreInfo.proto";

message VintageMarketInfo {
	repeated VintageMarketStoreInfo open_store_list = 5;
	VintageMarketDealInfo deal_info = 8;
	repeated uint32 PKBPBFPHBHG = 6;
	repeated uint32 FDIJBAICFIN = 3;
	repeated uint32 LDMCLAIHOON = 1518;
	repeated uint32 ONNGBJMAFAC = 4;
	map<uint32, bool> bargain_info_map = 12;
	repeated uint32 FDEKIOGEOFI = 1;
	bool MCEKANOEHBO = 7;
	bool MDDABHIEBKK = 9;
	bool BOGGBKMMLDL = 2;
	bool BHBFPPPFNIK = 14;
	uint32 FNKIDHNDLII = 10;
	uint32 store_round = 15;
	uint32 help_skill_id = 314;
	uint32 CDFEHJKKEJE = 82;
	uint32 LHBCCNFGCHK = 443;
	bool OFMOCOGFFEA = 11;
	bool KAFHHLIFPFL = 415;
	bool CGLABDKCKDF = 1831;
	bool CGKINBNKLEJ = 179;
	uint32 CNADHCNPMDL = 13;
}
